import type { PricingLocale } from './locales';

// Explicit coverage: new buyer-facing labels must never inherit English.
const rows: Record<PricingLocale, readonly string[]> = {
  en: ['How many locations?', 'Choose all that apply. Specialist choices automatically include their paid extensions below.', 'Included for your business setup. Remove the business choice above to remove this extension.', 'You operate one brand, including outlets you run as a franchisee. You do not manage other franchise owners.', 'You operate several brands or types of business. Select any specialist activities you also manage.', 'Manage a franchise network', 'For franchisors who oversee franchise owners, royalties and network standards. If you only operate franchise outlets, choose Single brand or Diversified group.', 'Extensions are estimated across the locations entered above. If only part of your group needs them, we will confirm that scope in your proposal.'],
  ar: ['كم عدد المواقع؟', 'اختر كل ما ينطبق. الخيارات المتخصصة تضيف تلقائيًا الإضافات المدفوعة أدناه.', 'مشمول وفق إعداد أعمالك. أزل خيار الأعمال أعلاه لإزالة هذه الإضافة.', 'تدير علامة واحدة، بما فيها فروع تديرها بصفتك صاحب امتياز. لا تشرف على أصحاب امتياز آخرين.', 'تدير عدة علامات أو أنواع أعمال. اختر أيضًا الأنشطة المتخصصة التي تديرها.', 'إدارة شبكة امتياز', 'لمانحي الامتياز الذين يشرفون على أصحاب الامتياز والإتاوات ومعايير الشبكة. إذا كنت تدير فروع امتياز فقط، اختر علامة واحدة أو مجموعة متنوعة.', 'يُقدّر سعر الإضافات لجميع المواقع المُدخلة أعلاه. إذا احتاجها جزء من المجموعة فقط، نؤكد النطاق في عرضنا.'],
  fr: ['Combien de sites ?', 'Choisissez tout ce qui convient. Les activités spécialisées ajoutent automatiquement leurs extensions payantes ci-dessous.', 'Inclus pour votre activité. Retirez le choix ci-dessus pour retirer cette extension.', 'Vous exploitez une marque, y compris comme franchisé. Vous ne supervisez pas les autres franchisés.', 'Vous exploitez plusieurs marques ou types d’activité. Sélectionnez aussi vos activités spécialisées.', 'Gérer un réseau de franchises', 'Pour les franchiseurs qui supervisent franchisés, redevances et standards. Si vous exploitez uniquement des points de vente franchisés, choisissez Une marque ou Groupe diversifié.', 'Les extensions sont estimées pour les sites saisis. Si seule une partie du groupe en a besoin, nous confirmerons le périmètre dans la proposition.'],
  es: ['¿Cuántas ubicaciones?', 'Elige todo lo que corresponda. Las actividades especializadas añaden automáticamente sus extensiones de pago.', 'Incluido por tu actividad. Quita la opción anterior para quitar esta extensión.', 'Operas una marca, incluso como franquiciado. No supervisas a otros propietarios de franquicias.', 'Operas varias marcas o tipos de negocio. Selecciona también tus actividades especializadas.', 'Gestionar una red de franquicias', 'Para franquiciadores que supervisan propietarios, regalías y estándares. Si solo operas locales franquiciados, elige Una marca o Grupo diversificado.', 'Las extensiones se estiman para todas las ubicaciones indicadas. Si solo parte del grupo las necesita, confirmaremos el alcance en la propuesta.'],
  de: ['Wie viele Standorte?', 'Wählen Sie alles Zutreffende. Spezialbereiche fügen ihre kostenpflichtigen Erweiterungen automatisch hinzu.', 'Für Ihr Geschäftsmodell enthalten. Entfernen Sie die Auswahl oben, um diese Erweiterung zu entfernen.', 'Sie betreiben eine Marke, auch als Franchisenehmer. Sie beaufsichtigen keine anderen Franchiseinhaber.', 'Sie betreiben mehrere Marken oder Geschäftsarten. Wählen Sie auch Ihre Spezialbereiche.', 'Ein Franchisenetzwerk führen', 'Für Franchisegeber, die Inhaber, Gebühren und Standards betreuen. Betreiben Sie nur Franchisefilialen, wählen Sie Eine Marke oder Diversifizierte Gruppe.', 'Erweiterungen werden für alle eingegebenen Standorte geschätzt. Benötigt sie nur ein Teil der Gruppe, bestätigen wir den Umfang im Angebot.'],
  nl: ['Hoeveel locaties?', 'Kies alles wat past. Specialistische activiteiten voegen hun betaalde uitbreidingen automatisch toe.', 'Inbegrepen voor uw bedrijfsopzet. Verwijder de keuze hierboven om deze uitbreiding te verwijderen.', 'U exploiteert één merk, ook als franchisenemer. U houdt geen toezicht op andere franchisehouders.', 'U exploiteert meerdere merken of bedrijfstypen. Selecteer ook uw specialistische activiteiten.', 'Een franchisenetwerk beheren', 'Voor franchisegevers die houders, royalty’s en normen beheren. Exploiteert u alleen franchiselocaties, kies dan Eén merk of Gediversifieerde groep.', 'Uitbreidingen worden voor alle ingevoerde locaties geschat. Als slechts een deel ze nodig heeft, bevestigen we de omvang in het voorstel.'],
  pt: ['Quantas unidades?', 'Selecione tudo o que se aplica. Atividades especializadas incluem automaticamente as suas extensões pagas.', 'Incluído para o seu negócio. Remova a escolha acima para remover esta extensão.', 'Opera uma marca, incluindo como franqueado. Não supervisiona outros proprietários de franquias.', 'Opera várias marcas ou tipos de negócio. Selecione também as atividades especializadas.', 'Gerir uma rede de franquias', 'Para franqueadores que supervisionam proprietários, royalties e padrões. Se apenas opera unidades franqueadas, escolha Uma marca ou Grupo diversificado.', 'As extensões são estimadas para todas as unidades indicadas. Se apenas parte do grupo precisar, confirmaremos o âmbito na proposta.'],
  hi: ['कितने स्थान हैं?', 'सभी लागू विकल्प चुनें। विशेष गतिविधियाँ अपने सशुल्क विस्तार अपने आप जोड़ती हैं।', 'आपके व्यवसाय के लिए शामिल है। इसे हटाने के लिए ऊपर का व्यवसाय विकल्प हटाएँ।', 'आप एक ब्रांड चलाते हैं, फ्रैंचाइज़ी संचालक के रूप में भी। आप अन्य फ्रैंचाइज़ी मालिकों का प्रबंधन नहीं करते।', 'आप कई ब्रांड या प्रकार के व्यवसाय चलाते हैं। अपनी विशेष गतिविधियाँ भी चुनें।', 'फ्रैंचाइज़ी नेटवर्क का प्रबंधन', 'फ्रैंचाइज़ी मालिकों, रॉयल्टी और मानकों की निगरानी करने वाले फ्रैंचाइज़र के लिए। केवल फ्रैंचाइज़ी दुकानें चलाते हैं तो एक ब्रांड या विविध समूह चुनें।', 'विस्तार का अनुमान ऊपर दर्ज सभी स्थानों के लिए है। केवल कुछ स्थानों को ज़रूरत हो तो प्रस्ताव में दायरा तय करेंगे।'],
  ur: ['کتنے مقامات ہیں؟', 'تمام متعلقہ اختیارات منتخب کریں۔ خصوصی سرگرمیاں اپنی بامعاوضہ توسیعات خود شامل کرتی ہیں۔', 'آپ کے کاروبار کے لیے شامل ہے۔ اسے ہٹانے کے لیے اوپر کاروبار کا انتخاب ہٹائیں۔', 'آپ ایک برانڈ چلاتے ہیں، فرنچائز آپریٹر کے طور پر بھی۔ آپ دیگر فرنچائز مالکان کی نگرانی نہیں کرتے۔', 'آپ کئی برانڈ یا کاروباری اقسام چلاتے ہیں۔ اپنی خصوصی سرگرمیاں بھی منتخب کریں۔', 'فرنچائز نیٹ ورک کی نگرانی', 'فرنچائز مالکان، رائلٹی اور معیار کی نگرانی کرنے والے فرنچائزر کے لیے۔ صرف فرنچائز دکانیں چلاتے ہیں تو ایک برانڈ یا متنوع گروپ منتخب کریں۔', 'توسیعات کا تخمینہ اوپر درج تمام مقامات کے لیے ہے۔ صرف بعض مقامات کو ضرورت ہو تو تجویز میں دائرہ طے کریں گے۔'],
  it: ['Quante sedi?', 'Seleziona tutto ciò che si applica. Le attività specialistiche aggiungono automaticamente le estensioni a pagamento.', 'Incluso per la tua attività. Rimuovi la scelta sopra per rimuovere questa estensione.', 'Gestisci un marchio, anche come affiliato. Non supervisioni altri proprietari in franchising.', 'Gestisci più marchi o tipi di attività. Seleziona anche le attività specialistiche.', 'Gestire una rete in franchising', 'Per gli affilianti che supervisionano affiliati, royalties e standard. Se gestisci solo punti vendita affiliati, scegli Un marchio o Gruppo diversificato.', 'Le estensioni sono stimate per tutte le sedi indicate. Se servono solo a parte del gruppo, confermeremo l’ambito nella proposta.'],
  pl: ['Ile lokalizacji?', 'Wybierz wszystkie pasujące opcje. Działalności specjalistyczne automatycznie dodają płatne rozszerzenia.', 'Uwzględnione dla Twojej działalności. Usuń wybór powyżej, aby usunąć rozszerzenie.', 'Prowadzisz jedną markę, także jako franczyzobiorca. Nie nadzorujesz innych właścicieli franczyzy.', 'Prowadzisz wiele marek lub rodzajów działalności. Wybierz także działalności specjalistyczne.', 'Zarządzać siecią franczyzową', 'Dla franczyzodawców nadzorujących właścicieli, opłaty i standardy. Jeśli prowadzisz tylko lokale franczyzowe, wybierz Jedna marka lub Zróżnicowana grupa.', 'Rozszerzenia są szacowane dla wszystkich podanych lokalizacji. Jeśli potrzebuje ich tylko część grupy, potwierdzimy zakres w ofercie.'],
  tr: ['Kaç konum var?', 'Geçerli tüm seçenekleri seçin. Uzmanlık faaliyetleri ücretli eklentilerini otomatik ekler.', 'İş modeliniz için dahil edildi. Bu eklentiyi kaldırmak için yukarıdaki iş seçimini kaldırın.', 'Franchise işletmecisi olarak da tek marka işletirsiniz. Diğer franchise sahiplerini yönetmezsiniz.', 'Birden fazla marka veya iş türü işletirsiniz. Uzmanlık faaliyetlerinizi de seçin.', 'Franchise ağını yönetmek', 'Sahipleri, lisans ücretlerini ve standartları yöneten franchise verenler içindir. Yalnızca franchise şubeleri işletiyorsanız Tek marka veya Çeşitlendirilmiş grup seçin.', 'Eklentiler girilen tüm konumlar için hesaplanır. Yalnızca grubun bir kısmı ihtiyaç duyuyorsa kapsamı teklifte doğrularız.'],
  'zh-Hans': ['有多少个地点？', '选择所有适用项。专业业务会自动加入相应的付费扩展。', '已按您的业务选择加入。取消上方业务选项即可移除此扩展。', '您经营一个品牌，包括作为加盟商经营门店，但不管理其他加盟商。', '您经营多个品牌或不同类型的业务。也请选择您管理的专业业务。', '管理加盟网络', '适用于管理加盟商、特许权使用费和网络标准的特许经营总部。若您只经营加盟门店，请选择单一品牌或多元化集团。', '扩展费用按上方填写的所有地点估算。如果只有部分地点需要，我们会在方案中确认范围。'],
  ja: ['拠点はいくつありますか？', '該当するものをすべて選択してください。専門業務には有料の拡張機能が自動追加されます。', '業務の選択により含まれています。削除するには上の業務選択を解除してください。', '加盟店としての運営を含め、一つのブランドを運営しています。他の加盟店オーナーは管理しません。', '複数のブランドや業態を運営しています。専門業務も選択してください。', 'フランチャイズ網を管理', '加盟店、ロイヤルティ、運営基準を管理する本部向けです。加盟店の運営のみなら単一ブランドまたは多角化グループを選択してください。', '拡張機能は入力した全拠点で見積もります。一部のみ必要な場合は提案時に範囲を確認します。'],
  ko: ['지점이 몇 개인가요?', '해당 항목을 모두 선택하세요. 전문 사업을 선택하면 유료 확장 기능이 자동으로 추가됩니다.', '사업 선택에 따라 포함되었습니다. 제거하려면 위의 사업 선택을 해제하세요.', '가맹점 운영을 포함하여 하나의 브랜드를 운영합니다. 다른 가맹점주는 관리하지 않습니다.', '여러 브랜드나 업종을 운영합니다. 전문 사업도 선택하세요.', '프랜차이즈 네트워크 관리', '가맹점주, 로열티와 운영 기준을 관리하는 본사용입니다. 가맹점만 운영한다면 단일 브랜드 또는 다각화 그룹을 선택하세요.', '확장 기능은 입력한 모든 지점을 기준으로 예상합니다. 일부만 필요하다면 제안서에서 범위를 확인합니다.'],
  id: ['Berapa lokasi?', 'Pilih semua yang sesuai. Kegiatan khusus otomatis menambahkan ekstensi berbayarnya.', 'Termasuk untuk bisnis Anda. Hapus pilihan bisnis di atas untuk menghapus ekstensi ini.', 'Anda menjalankan satu merek, termasuk sebagai penerima waralaba. Anda tidak mengawasi pemilik waralaba lain.', 'Anda menjalankan beberapa merek atau jenis bisnis. Pilih juga kegiatan khusus yang dikelola.', 'Mengelola jaringan waralaba', 'Untuk pemberi waralaba yang mengawasi pemilik, royalti dan standar. Jika hanya menjalankan gerai waralaba, pilih Satu merek atau Grup beragam.', 'Ekstensi diperkirakan untuk semua lokasi yang dimasukkan. Jika hanya sebagian grup membutuhkan, cakupan dikonfirmasi dalam proposal.'],
  vi: ['Có bao nhiêu địa điểm?', 'Chọn tất cả mục phù hợp. Hoạt động chuyên biệt tự động thêm phần mở rộng có phí.', 'Được thêm theo mô hình kinh doanh. Bỏ lựa chọn phía trên để bỏ phần mở rộng này.', 'Bạn vận hành một thương hiệu, kể cả với tư cách bên nhận nhượng quyền. Bạn không quản lý các chủ nhượng quyền khác.', 'Bạn vận hành nhiều thương hiệu hoặc loại hình kinh doanh. Chọn thêm các hoạt động chuyên biệt.', 'Quản lý mạng lưới nhượng quyền', 'Dành cho bên nhượng quyền quản lý chủ cơ sở, tiền bản quyền và tiêu chuẩn. Nếu chỉ vận hành cửa hàng nhận nhượng quyền, chọn Một thương hiệu hoặc Tập đoàn đa dạng.', 'Phần mở rộng được ước tính cho tất cả địa điểm đã nhập. Nếu chỉ một phần cần, chúng tôi sẽ xác nhận phạm vi trong đề xuất.'],
  ro: ['Câte locații?', 'Selectați tot ce se aplică. Activitățile specializate adaugă automat extensiile plătite.', 'Inclus pentru activitatea dvs. Eliminați alegerea de mai sus pentru a elimina extensia.', 'Operați un brand, inclusiv ca francizat. Nu supravegheați alți proprietari de francize.', 'Operați mai multe branduri sau tipuri de activități. Selectați și activitățile specializate.', 'Gestionarea unei rețele de francize', 'Pentru francizori care supraveghează proprietari, redevențe și standarde. Dacă operați doar locații francizate, alegeți Un brand sau Grup diversificat.', 'Extensiile sunt estimate pentru toate locațiile introduse. Dacă doar o parte are nevoie, confirmăm domeniul în ofertă.'],
  sv: ['Hur många platser?', 'Välj allt som gäller. Specialistverksamheter lägger automatiskt till sina betalda tillägg.', 'Ingår för din verksamhet. Ta bort valet ovan för att ta bort tillägget.', 'Du driver ett varumärke, även som franchisetagare. Du övervakar inte andra franchiseägare.', 'Du driver flera varumärken eller verksamhetstyper. Välj även dina specialistverksamheter.', 'Hantera ett franchisenätverk', 'För franchisegivare som övervakar ägare, avgifter och standarder. Driver du endast franchiseenheter, välj Ett varumärke eller Diversifierad grupp.', 'Tillägg uppskattas för alla angivna platser. Om bara en del behöver dem bekräftar vi omfattningen i förslaget.'],
  bn: ['কতটি স্থান আছে?', 'প্রযোজ্য সব বিকল্প বেছে নিন। বিশেষ কার্যক্রম স্বয়ংক্রিয়ভাবে তাদের মূল্যযুক্ত এক্সটেনশন যোগ করে।', 'আপনার ব্যবসার জন্য অন্তর্ভুক্ত। এটি সরাতে উপরের ব্যবসার বিকল্প সরান।', 'আপনি একটি ব্র্যান্ড চালান, ফ্র্যাঞ্চাইজি হিসেবেও। অন্য ফ্র্যাঞ্চাইজি মালিকদের তদারকি করেন না।', 'আপনি একাধিক ব্র্যান্ড বা ব্যবসার ধরন চালান। বিশেষ কার্যক্রমও বেছে নিন।', 'ফ্র্যাঞ্চাইজি নেটওয়ার্ক পরিচালনা', 'মালিক, রয়্যালটি ও মান তদারকি করা ফ্র্যাঞ্চাইজরের জন্য। শুধু ফ্র্যাঞ্চাইজি দোকান চালালে একটি ব্র্যান্ড বা বৈচিত্র্যময় গ্রুপ বেছে নিন।', 'এক্সটেনশনের হিসাব সব দেওয়া স্থানের জন্য। শুধু কিছু স্থানে প্রয়োজন হলে প্রস্তাবে পরিধি নিশ্চিত করব।'],
  th: ['มีกี่สาขา?', 'เลือกทุกข้อที่ตรงกับธุรกิจ กิจกรรมเฉพาะทางจะเพิ่มส่วนเสริมที่มีค่าใช้จ่ายโดยอัตโนมัติ', 'รวมตามรูปแบบธุรกิจของคุณ หากต้องการนำออกให้ยกเลิกตัวเลือกธุรกิจด้านบน', 'คุณดำเนินงานหนึ่งแบรนด์ รวมถึงในฐานะผู้รับแฟรนไชส์ แต่ไม่ได้ดูแลเจ้าของแฟรนไชส์รายอื่น', 'คุณดำเนินงานหลายแบรนด์หรือหลายประเภทธุรกิจ เลือกกิจกรรมเฉพาะทางด้วย', 'บริหารเครือข่ายแฟรนไชส์', 'สำหรับเจ้าของระบบแฟรนไชส์ที่ดูแลผู้รับแฟรนไชส์ ค่าลิขสิทธิ์และมาตรฐาน หากเพียงดำเนินงานร้านแฟรนไชส์ให้เลือกแบรนด์เดียวหรือกลุ่มธุรกิจหลากหลาย', 'ส่วนเสริมประเมินสำหรับทุกสาขาที่กรอก หากต้องการเพียงบางส่วนเราจะยืนยันขอบเขตในข้อเสนอ'],
  ms: ['Berapa lokasi?', 'Pilih semua yang berkenaan. Aktiviti khusus menambah sambungan berbayar secara automatik.', 'Disertakan untuk perniagaan anda. Buang pilihan di atas untuk membuang sambungan ini.', 'Anda mengendalikan satu jenama, termasuk sebagai francaisi. Anda tidak menyelia pemilik francais lain.', 'Anda mengendalikan beberapa jenama atau jenis perniagaan. Pilih juga aktiviti khusus.', 'Mengurus rangkaian francais', 'Untuk pemberi francais yang menyelia pemilik, royalti dan piawaian. Jika hanya mengendalikan cawangan francais, pilih Satu jenama atau Kumpulan pelbagai.', 'Sambungan dianggarkan untuk semua lokasi yang dimasukkan. Jika hanya sebahagian memerlukan, skop disahkan dalam cadangan.'],
  az: ['Neçə məkan var?', 'Uyğun olanları seçin. Xüsusi fəaliyyətlər ödənişli əlavələrini avtomatik əlavə edir.', 'Biznes seçiminizə görə daxildir. Bu əlavəni silmək üçün yuxarıdakı biznes seçimini silin.', 'Françayzi kimi də bir brend idarə edirsiniz. Digər françayz sahiblərinə nəzarət etmirsiniz.', 'Bir neçə brend və ya biznes növünü idarə edirsiniz. Xüsusi fəaliyyətlərinizi də seçin.', 'Françayz şəbəkəsini idarə etmək', 'Sahiblərə, royaltilərə və standartlara nəzarət edən françayzerlər üçündür. Yalnız françayz məkanları işlədirsinizsə, Tək brend və ya Şaxələndirilmiş qrup seçin.', 'Əlavələr daxil edilən bütün məkanlar üçün hesablanır. Yalnız bir hissə ehtiyac duyursa, əhatəni təklifdə təsdiqləyəcəyik.'],
  ru: ['Сколько локаций?', 'Выберите всё подходящее. Специальные направления автоматически добавляют платные дополнения ниже.', 'Включено по вашему выбору бизнеса. Чтобы убрать дополнение, отмените выбор выше.', 'Вы управляете одним брендом, в том числе как франчайзи. Вы не контролируете других владельцев франшиз.', 'Вы управляете несколькими брендами или видами бизнеса. Выберите также специальные направления.', 'Управлять франчайзинговой сетью', 'Для франчайзеров, контролирующих владельцев, роялти и стандарты сети. Если вы только управляете франчайзинговыми точками, выберите Один бренд или Диверсифицированная группа.', 'Дополнения рассчитаны для всех указанных локаций. Если они нужны только части группы, подтвердим охват в предложении.'],
  pap: ['Kuantu lokashon?', 'Skohe tur loke ta apliká. Aktividatnan spesial ta agrega nan ekstensions pagá automáticamente.', 'Inkluí pa bo negoshi. Kita e selekshon ariba pa kita e ekstension aki.', 'Bo ta opera un marka, tambe komo franquisiado. Bo no ta supervisá otro doño di frankisia.', 'Bo ta opera varios marka òf tipo di negoshi. Skohe tambe bo aktividatnan spesial.', 'Manehá un red di frankisia', 'Pa franquisiador ku ta supervisá doñonan, royalty i normanan. Si bo ta opera solamente lokalnan di frankisia, skohe Un marka òf Grupo diversifiká.', 'Ekstensions ta wordu estimá pa tur lokashon yena. Si solamente un parti mester nan, nos ta konfirmá e alkance den e proposishon.'],
};
export function getBuyerJourneyCopy(locale: PricingLocale) {
  const [locationQuestion, selectionNote, linked, singleHelp, multiHelp, franchiseLabel, franchiseHelp, coverage] = rows[locale];
  return { locationQuestion, selectionNote, linked, singleHelp, multiHelp, franchiseLabel, franchiseHelp, coverage };
}
