// New bill-affecting disclosures for the supported auxiliary locales.
export const buyerAuxiliaryCopy = {
  de: {
    title:'Preise passend zu Ihrem Unternehmen.',subtitle:'Bedarf wählen. Preis sehen. Bei Bedarf verfeinern.',business:'Wie ist Ihr Unternehmen organisiert?',models:['Eine Marke','Diversifizierte Gruppe','Franchisenetz','Hotelgastronomie','Cloud Kitchen','Catering und Events','Produktion und Zentralküche'],workforce:'Einmalig gezählte Mitarbeitende an allen Standorten',workforceHint:'Jede Person einmal zählen. Leer lassen für eine Basisschätzung.',allowance:'Mitarbeitende in Ihrer Gruppe enthalten',overage:'Zusätzliche Mitarbeiterplätze',overageNote:'Zusätzliche Plätze werden einmal zum höchsten geltenden Satz berechnet, anteilig und bis zum Ende der Aboperiode gebunden. Weniger Personal führt nicht automatisch zu Gutschriften.',workforceUnknown:'Zusätzliche Personalkosten sind ohne Mitarbeiterzahl ausgeschlossen.',payroll:'Land der Lohnabrechnung',payrollNote:'Verfügbarkeit, gesetzliche Vorgaben und Einrichtung müssen für Ihr Land bestätigt werden.',commitment:'Laufzeit und Zahlung',terms:['Monatlich · laufend','Jährlich · quartalsweise bezahlt','Jährlich · im Voraus bezahlt','2 Jahre · im Voraus bezahlt'],scoped:'Vor Aktivierung separat festgelegt',specialist:'Spezialumfang und Objektfreigrenzen werden im Angebot bestätigt. Zusätzliche Objektkosten sind in dieser Schätzung ausgeschlossen.',intentNote:'Dies ist eine Schätzung, kein Festangebot. Preise und Berechtigung werden vor Aktivierung erneut geprüft.'
  },
  nl: {
    title:'Prijzen die bij je bedrijf passen.',subtitle:'Kies je behoeften. Bekijk je prijs. Verfijn wanneer je wilt.',business:'Hoe is je bedrijf georganiseerd?',models:['Eén merk','Gediversifieerde groep','Franchisenetwerk','Hotelhoreca','Cloud Kitchen','Catering en evenementen','Productie en centrale keuken'],workforce:'Unieke medewerkers op al je locaties',workforceHint:'Tel elke persoon één keer. Laat leeg voor een basisraming.',allowance:'medewerkers inbegrepen in je groep',overage:'Extra medewerkersplaatsen',overageNote:'Extra plaatsen worden één keer tegen het hoogste toepasselijke tarief berekend, naar rato en vastgelegd tot het einde van de abonnementsperiode. Minder personeel levert niet automatisch tegoed op.',workforceUnknown:'Extra personeelskosten zijn uitgesloten zolang het aantal onbekend is.',payroll:'Land van loonadministratie',payrollNote:'Beschikbaarheid, wettelijke eisen en inrichting moeten voor je land worden bevestigd.',commitment:'Looptijd en betaling',terms:['Maandelijks · doorlopend','Jaarlijks · per kwartaal betaald','Jaarlijks · vooruitbetaald','2 jaar · vooruitbetaald'],scoped:'Apart bepaald vóór activering',specialist:'Specialistische scope en objectlimieten worden in een voorstel bevestigd. Extra objectkosten zijn uitgesloten van deze raming.',intentNote:'Dit is een raming, geen vaste offerte. Prijzen en geschiktheid worden vóór activering opnieuw gecontroleerd.'
  },
  pt: {
    title:'Preços que se ajustam ao seu negócio.',subtitle:'Escolha o que precisa. Veja o preço. Ajuste quando quiser.',business:'Como seu negócio está organizado?',models:['Uma marca','Grupo diversificado','Rede de franquias','Alimentação hoteleira','Cloud Kitchen','Catering e eventos','Produção e cozinha central'],workforce:'Funcionários únicos em todas as unidades',workforceHint:'Conte cada pessoa uma vez. Deixe vazio para uma estimativa base.',allowance:'funcionários incluídos no grupo',overage:'Vagas adicionais de funcionários',overageNote:'Vagas adicionais são cobradas uma vez pela maior tarifa aplicável, proporcionalmente e até o fim do período da assinatura. Reduções não geram créditos automáticos.',workforceUnknown:'Custos de funcionários adicionais excluídos até informar o total.',payroll:'País da folha de pagamento',payrollNote:'Cobertura, exigências legais e implementação devem ser confirmadas para seu país.',commitment:'Compromisso e pagamento',terms:['Mensal · recorrente','Anual · pago trimestralmente','Anual · pago antecipadamente','2 anos · pagos antecipadamente'],scoped:'Definido separadamente antes da ativação',specialist:'O escopo especializado e as franquias de objetos serão confirmados na proposta. Custos de objetos adicionais estão excluídos.',intentNote:'Esta é uma estimativa, não uma proposta fixa. Preços e elegibilidade são verificados antes da ativação.'
  },
  it: {
    title:'Prezzi adatti alla tua attività.',subtitle:'Scegli cosa ti serve. Guarda il prezzo. Affina quando vuoi.',business:'Come è organizzata la tua attività?',models:['Un marchio','Gruppo diversificato','Rete in franchising','Ristorazione alberghiera','Cloud Kitchen','Catering ed eventi','Produzione e cucina centrale'],workforce:'Dipendenti unici in tutte le sedi',workforceHint:'Conta ogni persona una volta. Lascia vuoto per una stima di base.',allowance:'dipendenti inclusi nel gruppo',overage:'Posti aggiuntivi per dipendenti',overageNote:'I posti aggiuntivi sono addebitati una volta alla tariffa applicabile più alta, pro rata e fino alla fine del periodo di abbonamento. Le riduzioni non generano crediti automatici.',workforceUnknown:'Costi per dipendenti aggiuntivi esclusi finché il numero non è indicato.',payroll:'Paese delle paghe',payrollNote:'Copertura, requisiti legali e implementazione devono essere confermati per il tuo paese.',commitment:'Durata e pagamento',terms:['Mensile · continuativo','Annuale · pagato trimestralmente','Annuale · pagato in anticipo','2 anni · pagati in anticipo'],scoped:'Definito separatamente prima dell’attivazione',specialist:'Ambito specialistico e limiti degli oggetti saranno confermati nella proposta. I costi degli oggetti aggiuntivi sono esclusi.',intentNote:'È una stima, non un preventivo fisso. Prezzi e idoneità saranno verificati prima dell’attivazione.'
  },
  pl: {
    title:'Ceny dopasowane do Twojej firmy.',subtitle:'Wybierz potrzeby. Zobacz cenę. Doprecyzuj, gdy zechcesz.',business:'Jak zorganizowana jest Twoja firma?',models:['Jedna marka','Zróżnicowana grupa','Sieć franczyzowa','Gastronomia hotelowa','Cloud Kitchen','Catering i wydarzenia','Produkcja i kuchnia centralna'],workforce:'Unikalni pracownicy we wszystkich lokalizacjach',workforceHint:'Licz każdą osobę raz. Zostaw puste, aby uzyskać podstawowy szacunek.',allowance:'pracowników wliczonych dla grupy',overage:'Dodatkowe miejsca dla pracowników',overageNote:'Dodatkowe miejsca są rozliczane raz według najwyższej obowiązującej stawki, proporcjonalnie i do końca okresu abonamentu. Spadek zatrudnienia nie tworzy automatycznie zwrotów.',workforceUnknown:'Opłaty za dodatkowych pracowników wyłączone do podania liczby.',payroll:'Kraj rozliczania płac',payrollNote:'Dostępność, wymogi prawne i wdrożenie wymagają potwierdzenia dla Twojego kraju.',commitment:'Okres umowy i płatność',terms:['Miesięcznie · odnawialnie','Rocznie · płatność kwartalna','Rocznie · płatność z góry','2 lata · płatność z góry'],scoped:'Ustalane osobno przed aktywacją',specialist:'Zakres specjalistyczny i limity obiektów zostaną potwierdzone w propozycji. Opłaty za dodatkowe obiekty są wyłączone.',intentNote:'To szacunek, nie stała oferta. Ceny i uprawnienia są ponownie sprawdzane przed aktywacją.'
  },
  tr: {
    title:'İşletmenize uygun fiyatlar.',subtitle:'İhtiyacınızı seçin. Fiyatınızı görün. Hazır olduğunuzda ayrıntılandırın.',business:'İşletmeniz nasıl yapılandırılmış?',models:['Tek marka','Çeşitlendirilmiş grup','Franchise ağı','Otel yiyecek ve içecek','Cloud Kitchen','Catering ve etkinlikler','Üretim ve merkez mutfak'],workforce:'Tüm lokasyonlardaki benzersiz çalışan sayısı',workforceHint:'Her kişiyi bir kez sayın. Temel tahmin için boş bırakın.',allowance:'grubunuzda dahil olan çalışan',overage:'Ek çalışan kapasitesi',overageNote:'Ek kapasite geçerli en yüksek oranla bir kez, orantılı olarak ve abonelik dönemi sonuna kadar ücretlendirilir. Personel azalması otomatik alacak oluşturmaz.',workforceUnknown:'Çalışan sayısı belirtilene kadar ek çalışan ücretleri hariçtir.',payroll:'Bordro ülkesi',payrollNote:'Ülkeniz için kapsam, yasal gereklilikler ve kurulum teyit edilmelidir.',commitment:'Taahhüt ve ödeme',terms:['Aylık · yenilenen','Yıllık · üç ayda bir ödeme','Yıllık · peşin ödeme','2 yıl · peşin ödeme'],scoped:'Etkinleştirmeden önce ayrıca belirlenir',specialist:'Uzmanlık kapsamı ve nesne limitleri teklifte teyit edilir. Ek nesne ücretleri bu tahmine dahil değildir.',intentNote:'Bu bir tahmindir, sabit teklif değildir. Fiyatlar ve uygunluk etkinleştirmeden önce tekrar kontrol edilir.'
  },
  ro: {
    title:'Prețuri potrivite afacerii tale.',subtitle:'Alege ce îți trebuie. Vezi prețul. Ajustează când dorești.',business:'Cum este organizată afacerea ta?',models:['O marcă','Grup diversificat','Rețea de francize','Restaurante hoteliere','Cloud Kitchen','Catering și evenimente','Producție și bucătărie centrală'],workforce:'Angajați unici în toate locațiile',workforceHint:'Numără fiecare persoană o dată. Lasă gol pentru estimarea de bază.',allowance:'angajați incluși în grup',overage:'Locuri suplimentare pentru angajați',overageNote:'Locurile suplimentare se facturează o dată la cel mai mare tarif aplicabil, proporțional și până la sfârșitul perioadei abonamentului. Reducerile de personal nu generează credite automat.',workforceUnknown:'Costurile angajaților suplimentari sunt excluse până la precizarea numărului.',payroll:'Țara salarizării',payrollNote:'Acoperirea, cerințele legale și implementarea trebuie confirmate pentru țara ta.',commitment:'Durată și plată',terms:['Lunar · recurent','Anual · plătit trimestrial','Anual · plătit în avans','2 ani · plătiți în avans'],scoped:'Stabilit separat înainte de activare',specialist:'Domeniul specializat și limitele obiectelor sunt confirmate în propunere. Costurile obiectelor suplimentare sunt excluse.',intentNote:'Este o estimare, nu o ofertă fixă. Prețurile și eligibilitatea sunt reverificate înainte de activare.'
  },
  sv: {
    title:'Priser som passar din verksamhet.',subtitle:'Välj vad du behöver. Se priset. Förfina när du vill.',business:'Hur är din verksamhet organiserad?',models:['Ett varumärke','Diversifierad grupp','Franchisenätverk','Hotellrestauranger','Cloud Kitchen','Catering och evenemang','Produktion och centralkök'],workforce:'Unika medarbetare på alla platser',workforceHint:'Räkna varje person en gång. Lämna tomt för en grunduppskattning.',allowance:'medarbetare ingår i gruppen',overage:'Extra medarbetarplatser',overageNote:'Extra platser debiteras en gång till högsta tillämpliga pris, proportionellt och låst till abonnemangsperiodens slut. Minskad personal ger inte automatiskt krediter.',workforceUnknown:'Avgifter för extra medarbetare exkluderas tills antalet anges.',payroll:'Löneland',payrollNote:'Täckning, lagkrav och införande måste bekräftas för ditt land.',commitment:'Avtalstid och betalning',terms:['Månadsvis · löpande','Årligen · betalas kvartalsvis','Årligen · betalas i förskott','2 år · betalas i förskott'],scoped:'Fastställs separat före aktivering',specialist:'Specialistomfattning och objektsgränser bekräftas i ett förslag. Avgifter för extra objekt ingår inte.',intentNote:'Detta är en uppskattning, inte en fast offert. Priser och behörighet kontrolleras före aktivering.'
  },
  'zh-Hans': {
    title:'适合您业务的定价。',subtitle:'选择所需功能。查看价格。准备好后再细化。',business:'您的业务如何组织？',models:['单一品牌','多元化集团','特许经营网络','酒店餐饮','云厨房','餐饮承办与活动','生产与中央厨房'],workforce:'所有门店的独立员工人数',workforceHint:'每人只计算一次。留空可查看基础估算。',allowance:'名员工包含在集团额度内',overage:'额外员工名额',overageNote:'额外名额按最高适用费率仅收费一次，按比例计算并锁定至订阅期结束。员工减少不会自动产生退款额度。',workforceUnknown:'在提供员工人数之前，估算不含额外员工费用。',payroll:'薪资所在国家',payrollNote:'需确认所在国家的薪资覆盖、法定要求和实施范围。',commitment:'承诺期限与付款',terms:['按月 · 滚动续订','按年 · 按季度付款','按年 · 预付','两年 · 预付'],scoped:'激活前另行确定',specialist:'专业范围和对象额度将在方案中确认。本估算不含额外对象费用。',intentNote:'此为估算，不是固定报价。激活前将重新核实价格和资格。'
  },
  ja: {
    title:'ビジネスに合った料金。',subtitle:'必要な機能を選択。料金を確認。準備ができたら詳細を調整。',business:'事業はどのように構成されていますか？',models:['単一ブランド','多角化グループ','フランチャイズ網','ホテル飲食','Cloud Kitchen','ケータリング・イベント','製造・中央厨房'],workforce:'全拠点の重複しない従業員数',workforceHint:'各人を一度だけ数えます。基本見積もりでは空欄にできます。',allowance:'人の従業員がグループ枠に含まれます',overage:'追加従業員枠',overageNote:'追加枠は適用される最高単価で一度だけ請求され、期間按分されて契約期間末まで固定されます。人数の減少で自動返金は発生しません。',workforceUnknown:'人数が未入力の場合、追加従業員料金は含まれません。',payroll:'給与計算の国',payrollNote:'国ごとの対応範囲、法的要件、導入内容の確認が必要です。',commitment:'契約期間と支払い',terms:['月単位・継続','年契約・四半期払い','年契約・前払い','2年契約・前払い'],scoped:'有効化前に別途決定',specialist:'専門機能の範囲と対象数の枠は提案時に確定します。追加対象の料金は含まれません。',intentNote:'これは概算であり、確定見積もりではありません。有効化前に料金と適用資格を再確認します。'
  },
  ko: {
    title:'비즈니스에 맞는 요금.',subtitle:'필요한 기능을 선택하세요. 가격을 확인하고 준비되면 세부 내용을 조정하세요.',business:'비즈니스는 어떻게 구성되어 있나요?',models:['단일 브랜드','다각화 그룹','프랜차이즈 네트워크','호텔 식음료','Cloud Kitchen','케이터링 및 행사','생산 및 중앙 주방'],workforce:'모든 지점의 중복 없는 직원 수',workforceHint:'각 사람을 한 번만 계산하세요. 기본 예상 가격은 비워 둘 수 있습니다.',allowance:'명이 그룹 포함 한도에 해당합니다',overage:'추가 직원 슬롯',overageNote:'추가 슬롯은 적용 가능한 최고 요율로 한 번만 청구되며 비례 계산 후 구독 기간 말까지 유지됩니다. 인원 감소가 자동 환급으로 이어지지는 않습니다.',workforceUnknown:'직원 수 입력 전에는 추가 직원 비용이 제외됩니다.',payroll:'급여 국가',payrollNote:'국가별 지원 범위, 법적 요건 및 구축 내용을 확인해야 합니다.',commitment:'약정 및 결제',terms:['월간 · 갱신','연간 · 분기별 결제','연간 · 선불','2년 · 선불'],scoped:'활성화 전에 별도로 산정',specialist:'전문 범위와 객체 한도는 제안서에서 확정됩니다. 추가 객체 요금은 제외됩니다.',intentNote:'이는 예상 금액이며 확정 견적이 아닙니다. 활성화 전 가격과 자격을 다시 확인합니다.'
  },
  id: {
    title:'Harga yang sesuai bisnis Anda.',subtitle:'Pilih kebutuhan. Lihat harga. Sesuaikan saat siap.',business:'Bagaimana bisnis Anda disusun?',models:['Satu merek','Grup beragam','Jaringan waralaba','F&B hotel','Cloud Kitchen','Katering dan acara','Produksi dan dapur pusat'],workforce:'Jumlah karyawan unik di seluruh lokasi',workforceHint:'Hitung setiap orang sekali. Kosongkan untuk estimasi dasar.',allowance:'karyawan termasuk untuk grup',overage:'Slot karyawan tambahan',overageNote:'Slot tambahan ditagih sekali dengan tarif berlaku tertinggi, secara prorata dan terkunci hingga akhir periode langganan. Penurunan jumlah tidak otomatis menghasilkan kredit.',workforceUnknown:'Biaya karyawan tambahan dikecualikan sampai jumlah diisi.',payroll:'Negara penggajian',payrollNote:'Cakupan, persyaratan hukum, dan implementasi perlu dikonfirmasi untuk negara Anda.',commitment:'Komitmen dan pembayaran',terms:['Bulanan · berulang','Tahunan · dibayar triwulanan','Tahunan · dibayar di muka','2 tahun · dibayar di muka'],scoped:'Ditentukan terpisah sebelum aktivasi',specialist:'Cakupan khusus dan batas objek dikonfirmasi dalam proposal. Biaya objek tambahan dikecualikan.',intentNote:'Ini estimasi, bukan penawaran tetap. Harga dan kelayakan diperiksa kembali sebelum aktivasi.'
  },
  vi: {
    title:'Mức giá phù hợp với doanh nghiệp.',subtitle:'Chọn nhu cầu. Xem giá. Điều chỉnh khi sẵn sàng.',business:'Doanh nghiệp của bạn được tổ chức thế nào?',models:['Một thương hiệu','Tập đoàn đa dạng','Mạng lưới nhượng quyền','F&B khách sạn','Cloud Kitchen','Tiệc và sự kiện','Sản xuất và bếp trung tâm'],workforce:'Số nhân viên không trùng lặp tại các địa điểm',workforceHint:'Mỗi người chỉ tính một lần. Để trống để xem ước tính cơ bản.',allowance:'nhân viên được bao gồm trong nhóm',overage:'Suất nhân viên bổ sung',overageNote:'Suất bổ sung chỉ tính phí một lần theo mức áp dụng cao nhất, theo tỷ lệ và cố định đến cuối kỳ đăng ký. Giảm nhân sự không tự động tạo khoản tín dụng.',workforceUnknown:'Phí nhân viên bổ sung chưa được tính khi chưa có số lượng.',payroll:'Quốc gia tính lương',payrollNote:'Cần xác nhận phạm vi hỗ trợ, yêu cầu pháp lý và triển khai cho quốc gia của bạn.',commitment:'Cam kết và thanh toán',terms:['Hàng tháng · gia hạn','Hàng năm · trả hàng quý','Hàng năm · trả trước','2 năm · trả trước'],scoped:'Xác định riêng trước khi kích hoạt',specialist:'Phạm vi chuyên biệt và hạn mức đối tượng được xác nhận trong đề xuất. Phí đối tượng bổ sung chưa được tính.',intentNote:'Đây là ước tính, không phải báo giá cố định. Giá và điều kiện được kiểm tra lại trước khi kích hoạt.'
  },
  ms: {
    title:'Harga yang sesuai dengan perniagaan anda.',subtitle:'Pilih keperluan. Lihat harga. Perhalusi apabila bersedia.',business:'Bagaimana perniagaan anda disusun?',models:['Satu jenama','Kumpulan pelbagai','Rangkaian francais','F&B hotel','Cloud Kitchen','Katering dan acara','Pengeluaran dan dapur pusat'],workforce:'Pekerja unik di semua lokasi',workforceHint:'Kira setiap orang sekali. Biarkan kosong untuk anggaran asas.',allowance:'pekerja termasuk dalam kumpulan',overage:'Slot pekerja tambahan',overageNote:'Slot tambahan dicaj sekali pada kadar tertinggi yang berkenaan, secara prorata dan dikunci hingga akhir tempoh langganan. Pengurangan pekerja tidak menghasilkan kredit automatik.',workforceUnknown:'Caj pekerja tambahan dikecualikan sehingga bilangan diberikan.',payroll:'Negara penggajian',payrollNote:'Liputan, keperluan undang-undang dan pelaksanaan perlu disahkan untuk negara anda.',commitment:'Komitmen dan pembayaran',terms:['Bulanan · berulang','Tahunan · dibayar suku tahunan','Tahunan · dibayar awal','2 tahun · dibayar awal'],scoped:'Ditentukan berasingan sebelum pengaktifan',specialist:'Skop khusus dan had objek disahkan dalam cadangan. Caj objek tambahan dikecualikan.',intentNote:'Ini anggaran, bukan sebut harga tetap. Harga dan kelayakan disemak semula sebelum pengaktifan.'
  },
  hi: {
    title:'आपके व्यवसाय के अनुरूप कीमतें।',subtitle:'ज़रूरत चुनें। कीमत देखें। तैयार होने पर विवरण तय करें।',business:'आपका व्यवसाय कैसे संगठित है?',models:['एक ब्रांड','विविध समूह','फ्रैंचाइज़ नेटवर्क','होटल F&B','Cloud Kitchen','कैटरिंग और आयोजन','उत्पादन और केंद्रीय रसोई'],workforce:'सभी स्थानों पर अलग-अलग कर्मचारियों की संख्या',workforceHint:'हर व्यक्ति को एक बार गिनें। मूल अनुमान के लिए खाली छोड़ें।',allowance:'कर्मचारी आपके समूह में शामिल हैं',overage:'अतिरिक्त कर्मचारी स्थान',overageNote:'अतिरिक्त स्थान पर सबसे ऊँची लागू दर एक बार लगती है, अवधि के अनुपात में और सदस्यता अवधि के अंत तक तय रहती है। कर्मचारियों में कमी से अपने-आप क्रेडिट नहीं मिलता।',workforceUnknown:'संख्या देने तक अतिरिक्त कर्मचारी शुल्क शामिल नहीं हैं।',payroll:'वेतन का देश',payrollNote:'देश के लिए कवरेज, कानूनी आवश्यकताओं और कार्यान्वयन की पुष्टि करनी होगी।',commitment:'प्रतिबद्धता और भुगतान',terms:['मासिक · जारी','वार्षिक · तिमाही भुगतान','वार्षिक · अग्रिम भुगतान','2 वर्ष · अग्रिम भुगतान'],scoped:'सक्रिय करने से पहले अलग से तय होगा',specialist:'विशेष दायरे और ऑब्जेक्ट सीमा की पुष्टि प्रस्ताव में होगी। अतिरिक्त ऑब्जेक्ट शुल्क अनुमान में शामिल नहीं हैं।',intentNote:'यह अनुमान है, निश्चित कोटेशन नहीं। सक्रिय करने से पहले कीमत और पात्रता दोबारा जाँची जाती है।'
  },
  ur: {
    title:'آپ کے کاروبار کے مطابق قیمتیں۔',subtitle:'ضرورت منتخب کریں۔ قیمت دیکھیں۔ تیار ہوں تو تفصیل طے کریں۔',business:'آپ کا کاروبار کیسے منظم ہے؟',models:['ایک برانڈ','متنوع گروپ','فرنچائز نیٹ ورک','ہوٹل F&B','Cloud Kitchen','کیٹرنگ اور تقریبات','پیداوار اور مرکزی باورچی خانہ'],workforce:'تمام مقامات پر منفرد ملازمین کی تعداد',workforceHint:'ہر شخص کو ایک بار شمار کریں۔ بنیادی تخمینے کے لیے خالی چھوڑیں۔',allowance:'ملازمین آپ کے گروپ میں شامل ہیں',overage:'اضافی ملازمین کی گنجائش',overageNote:'اضافی گنجائش پر سب سے زیادہ لاگو شرح ایک بار، مدت کے تناسب سے اور رکنیت کی مدت کے اختتام تک لاگو ہوتی ہے۔ تعداد میں کمی خودکار کریڈٹ نہیں بناتی۔',workforceUnknown:'تعداد بتانے تک اضافی ملازمین کے اخراجات شامل نہیں ہیں۔',payroll:'تنخواہوں کا ملک',payrollNote:'آپ کے ملک کے لیے کوریج، قانونی تقاضوں اور نفاذ کی تصدیق ضروری ہے۔',commitment:'مدت اور ادائیگی',terms:['ماہانہ · جاری','سالانہ · سہ ماہی ادائیگی','سالانہ · پیشگی ادائیگی','2 سال · پیشگی ادائیگی'],scoped:'فعال کرنے سے پہلے الگ طے ہوگا',specialist:'خصوصی دائرہ اور اشیاء کی حد تجویز میں طے ہوگی۔ اضافی اشیاء کے اخراجات تخمینے میں شامل نہیں ہیں۔',intentNote:'یہ تخمینہ ہے، مقررہ کوٹیشن نہیں۔ فعال کرنے سے پہلے قیمت اور اہلیت دوبارہ جانچی جاتی ہے۔'
  },
  bn: {
    title:'আপনার ব্যবসার উপযোগী মূল্য।',subtitle:'প্রয়োজন বেছে নিন। মূল্য দেখুন। প্রস্তুত হলে বিস্তারিত ঠিক করুন।',business:'আপনার ব্যবসা কীভাবে সংগঠিত?',models:['একটি ব্র্যান্ড','বৈচিত্র্যময় গ্রুপ','ফ্র্যাঞ্চাইজি নেটওয়ার্ক','হোটেল F&B','Cloud Kitchen','ক্যাটারিং ও অনুষ্ঠান','উৎপাদন ও কেন্দ্রীয় রান্নাঘর'],workforce:'সব স্থানে অনন্য কর্মীর সংখ্যা',workforceHint:'প্রত্যেককে একবার গুনুন। প্রাথমিক আনুমানিক মূল্যের জন্য খালি রাখুন।',allowance:'জন কর্মী গ্রুপের সীমায় অন্তর্ভুক্ত',overage:'অতিরিক্ত কর্মী স্লট',overageNote:'অতিরিক্ত স্লটে সর্বোচ্চ প্রযোজ্য হারে একবার চার্জ হয়, সময়ের অনুপাতে এবং সাবস্ক্রিপশন মেয়াদ শেষ পর্যন্ত স্থির থাকে। কর্মী কমলে স্বয়ংক্রিয় ক্রেডিট হয় না।',workforceUnknown:'কর্মীর সংখ্যা না দেওয়া পর্যন্ত অতিরিক্ত কর্মী খরচ বাদ আছে।',payroll:'বেতন প্রদানের দেশ',payrollNote:'আপনার দেশের কভারেজ, আইনি শর্ত ও বাস্তবায়ন নিশ্চিত করতে হবে।',commitment:'অঙ্গীকার ও অর্থপ্রদান',terms:['মাসিক · চলমান','বার্ষিক · ত্রৈমাসিক পরিশোধ','বার্ষিক · অগ্রিম পরিশোধ','২ বছর · অগ্রিম পরিশোধ'],scoped:'সক্রিয় করার আগে আলাদাভাবে নির্ধারিত',specialist:'বিশেষ পরিসর ও অবজেক্ট সীমা প্রস্তাবে নিশ্চিত হবে। অতিরিক্ত অবজেক্ট খরচ এই অনুমানে নেই।',intentNote:'এটি অনুমান, স্থির কোটেশন নয়। সক্রিয় করার আগে মূল্য ও যোগ্যতা আবার যাচাই হবে।'
  },
  th: {
    title:'ราคาที่เหมาะกับธุรกิจของคุณ',subtitle:'เลือกสิ่งที่ต้องการ ดูราคา และปรับรายละเอียดเมื่อพร้อม',business:'ธุรกิจของคุณจัดโครงสร้างอย่างไร?',models:['แบรนด์เดียว','กลุ่มธุรกิจหลากหลาย','เครือข่ายแฟรนไชส์','อาหารและเครื่องดื่มโรงแรม','Cloud Kitchen','จัดเลี้ยงและอีเวนต์','การผลิตและครัวกลาง'],workforce:'จำนวนพนักงานไม่ซ้ำกันในทุกสาขา',workforceHint:'นับแต่ละคนครั้งเดียว เว้นว่างเพื่อดูประมาณการพื้นฐาน',allowance:'พนักงานที่รวมอยู่ในสิทธิ์ของกลุ่ม',overage:'สิทธิ์พนักงานเพิ่มเติม',overageNote:'สิทธิ์เพิ่มเติมคิดเพียงครั้งเดียวตามอัตราที่ใช้สูงสุด โดยคำนวณตามสัดส่วนและคงไว้จนสิ้นสุดรอบสมาชิก การลดจำนวนพนักงานไม่ทำให้เกิดเครดิตโดยอัตโนมัติ',workforceUnknown:'ยังไม่รวมค่าพนักงานเพิ่มเติมจนกว่าจะระบุจำนวน',payroll:'ประเทศสำหรับเงินเดือน',payrollNote:'ต้องยืนยันการรองรับ ข้อกำหนดกฎหมาย และการติดตั้งสำหรับประเทศของคุณ',commitment:'ระยะสัญญาและการชำระเงิน',terms:['รายเดือน · ต่อเนื่อง','รายปี · ชำระรายไตรมาส','รายปี · ชำระล่วงหน้า','2 ปี · ชำระล่วงหน้า'],scoped:'กำหนดแยกก่อนเปิดใช้งาน',specialist:'ขอบเขตเฉพาะและโควตาวัตถุจะยืนยันในข้อเสนอ ยังไม่รวมค่าวัตถุเพิ่มเติมในประมาณการนี้',intentNote:'นี่คือประมาณการ ไม่ใช่ใบเสนอราคาคงที่ จะตรวจสอบราคาและสิทธิ์อีกครั้งก่อนเปิดใช้งาน'
  },
  az: { title:'Biznesinizə uyğun qiymətlər.',subtitle:'Ehtiyacınızı seçin. Qiyməti görün. Hazır olduqda dəqiqləşdirin.',business:'Biznesiniz necə qurulub?',models:['Tək brend','Şaxələndirilmiş qrup','Françayz şəbəkəsi','Otel qida və içki','Bulud mətbəxi','Keyterinq və tədbirlər','İstehsal və mərkəzi mətbəx'],workforce:'Məkanlar üzrə unikal əməkdaşlar',workforceHint:'Hər şəxsi bir dəfə sayın. Əsas təxmin üçün boş saxlayın.',allowance:'əməkdaş qrupunuza daxildir',overage:'Əlavə əməkdaş yerləri',overageNote:'Əlavə yerlər ən yüksək uyğun tariflə bir dəfə hesablanır və abunə müddətinin sonuna qədər qüvvədə qalır.',workforceUnknown:'Əməkdaş sayı daxil edilənədək əlavə xərclər hesablanmır.',payroll:'Əməkhaqqı ölkəsi',payrollNote:'Ölkəniz üzrə əhatə, yerli tələblər və quraşdırma təsdiqlənməlidir.',commitment:'Öhdəlik və ödəniş',terms:['Aylıq · davamlı','İllik · rüblük ödəniş','İllik · əvvəlcədən ödəniş','2 il · əvvəlcədən ödəniş'],scoped:'Aktivləşdirmədən əvvəl ayrıca təsdiqlənir',specialist:'Xüsusi əhatə və obyekt limitləri təklifdə təsdiqlənəcək.',intentNote:'Bu təxmini qiymətdir, yekun təklif deyil. Qiymət və uyğunluq başlanmazdan əvvəl yoxlanacaq.' },
  ru: { title:'Цена, которая подходит вашему бизнесу.',subtitle:'Выберите нужное. Посмотрите цену. Уточните детали, когда будете готовы.',business:'Как устроен ваш бизнес?',models:['Один бренд','Диверсифицированная группа','Франчайзинговая сеть','Отельный F&B','Облачная кухня','Кейтеринг и мероприятия','Производство и центральная кухня'],workforce:'Уникальные сотрудники во всех локациях',workforceHint:'Считайте каждого человека один раз. Оставьте поле пустым для базового расчёта.',allowance:'сотрудников включено в группу',overage:'Дополнительные места для сотрудников',overageNote:'Дополнительные места оплачиваются один раз по максимальной применимой ставке до конца периода подписки.',workforceUnknown:'Дополнительные расходы не включены, пока число сотрудников не указано.',payroll:'Страна расчёта зарплаты',payrollNote:'Поддержка, требования закона и настройка должны быть подтверждены для вашей страны.',commitment:'Срок и оплата',terms:['Ежемесячно · с продлением','Ежегодно · поквартально','Ежегодно · предоплата','2 года · предоплата'],scoped:'Уточняется отдельно до активации',specialist:'Специализированный объём и лимиты объектов будут подтверждены в предложении.',intentNote:'Это расчёт, а не окончательное предложение. Перед активацией проверим цены и доступность.' },
  pap: { title:'Prijs ku ta pas ku bo negoshi.',subtitle:'Skohe loke bo mester. Mira e preis. Detaya esaki ora bo ta kla.',business:'Kon bo negoshi ta organisá?',models:['Un marka','Grupo diversifiká','Red di franquisia','F&B di hotel','Kushina den nube','Catering i eventonan','Produkshon i kushina sentral'],workforce:'Empleadonan unik den tur lokashon',workforceHint:'Konta kada persona un biaha. Laga bashi pa un estimashon basiko.',allowance:'empleadonan ta inkluí den bo grupo',overage:'Lugá pa empleado adishonal',overageNote:'Lugá adishonal ta wordu kargá un biaha te ku e periodo di suskripshon kaba.',workforceUnknown:'Kostonan di empleado adishonal no ta inkluí te ku bo yena e kantidat.',payroll:'Pais di pago di salario',payrollNote:'Kobertura, eksigensianan lokal i preparashon mester wordu konfirmá pa bo pais.',commitment:'Termino i pago',terms:['Mensual · kontinua','Anual · paga kada trimestre','Anual · paga adelantá','2 aña · paga adelantá'],scoped:'Ta wordu determiná apart promé ku aktivashon',specialist:'Alkance spesial i limitashon di objekto ta wordu konfirmá den e proposishon.',intentNote:'Esaki ta un estimashon, no un oferta final. Preis i disponobilidat ta wordu verifiká promé ku aktivashon.' },
} as const;

const actionKeys = ['choose','refine','review','need','estimate','exclusions','details','schedule','optional','enterprise','enterpriseBody','customCrew','foresight','share','copied','intentError','continue','payment','chooseCrew','roiHint'] as const;
const actionRows: Partial<Record<keyof typeof buyerAuxiliaryCopy, readonly string[]>> = {
  de: ['Plan wählen','Bedarf verfeinern','Schätzung prüfen','Was benötigen Sie?','Schätzung des Basisabonnements','USD · Steuern und einmalige Einrichtung ausgeschlossen','So wird Ihr Preis berechnet','Vollständige Preisstaffel anzeigen','Optional. Empfiehlt Erweiterungen, ohne Kosten hinzuzufügen.','Planen wir Ihr Portfolio.','Ab 250 Standorten oder bei individuellen Anforderungen erstellen wir ein Angebot.','Einzelne Crew-Funktionen wählen','Prognosen enthalten','Konfigurationslink kopieren','Link kopiert','Dieser Link ist ungültig oder enthält ein eingestelltes Angebot. Ihre Auswahl bleibt erhalten.','Weiter zu Sundae','Geschätzte Abonnementzahlung','Wählen Sie einen Crew-Plan für Ihre Schätzung.','Optionales Planungsmodell. Ergebnisse hängen von Ihren Daten und Maßnahmen ab.'],
  nl: ['Kies je plan','Verfijn je behoeften','Bekijk je raming','Wat heb je nodig?','Raming basisabonnement','USD · belastingen en eenmalige inrichting uitgesloten','Hoe je prijs wordt berekend','Bekijk alle prijsstaffels','Optioneel. Beveelt uitbreidingen aan zonder kosten toe te voegen.','Laten we je portfolio bepalen.','Voor 250+ locaties of maatwerk maken we een voorstel.','Kies individuele Crew-functies','Prognoses inbegrepen','Configuratielink kopiëren','Link gekopieerd','Deze link is ongeldig of gebruikt een vervallen aanbod. Je selectie blijft behouden.','Doorgaan naar Sundae','Geschatte abonnementsbetaling','Kies een Crew-plan voor je raming.','Optioneel planningsmodel. Resultaten hangen af van je gegevens en acties.'],
  pt: ['Escolha seu plano','Ajuste suas necessidades','Revise a estimativa','Do que você precisa?','Estimativa da assinatura base','USD · impostos e implementação inicial excluídos','Como seu preço é calculado','Ver todas as faixas de preço','Opcional. Recomenda extensões sem adicionar cobranças.','Vamos definir seu portfólio.','Para 250+ unidades ou necessidades específicas, preparamos uma proposta.','Escolher funções Crew individuais','Previsões incluídas','Copiar link da configuração','Link copiado','Este link é inválido ou usa uma oferta retirada. Sua seleção foi mantida.','Continuar para Sundae','Estimativa de pagamento da assinatura','Escolha um plano Crew para ver a estimativa.','Modelo de planejamento opcional. Os resultados dependem dos seus dados e ações.'],
  it: ['Scegli il piano','Affina le esigenze','Verifica la stima','Di cosa hai bisogno?','Stima dell’abbonamento base','USD · imposte e configurazione iniziale escluse','Come viene calcolato il prezzo','Vedi tutti gli scaglioni','Facoltativo. Consiglia estensioni senza aggiungere costi.','Definiamo il tuo portafoglio.','Per 250+ sedi o esigenze personalizzate prepariamo una proposta.','Scegli singole funzioni Crew','Previsioni incluse','Copia link della configurazione','Link copiato','Questo link non è valido o usa un’offerta ritirata. La selezione è stata mantenuta.','Continua su Sundae','Stima del pagamento dell’abbonamento','Scegli un piano Crew per vedere la stima.','Modello di pianificazione facoltativo. I risultati dipendono dai tuoi dati e azioni.'],
  pl: ['Wybierz plan','Doprecyzuj potrzeby','Sprawdź szacunek','Czego potrzebujesz?','Szacunkowy koszt podstawowej subskrypcji','USD · bez podatków i jednorazowego wdrożenia','Jak obliczamy cenę','Zobacz wszystkie progi cenowe','Opcjonalne. Rekomenduje rozszerzenia bez doliczania opłat.','Ustalmy zakres Twojej sieci.','Dla 250+ lokalizacji lub indywidualnych potrzeb przygotujemy ofertę.','Wybierz pojedyncze funkcje Crew','Prognozy w cenie','Kopiuj link konfiguracji','Link skopiowany','Link jest nieprawidłowy lub zawiera wycofaną ofertę. Twój wybór został zachowany.','Przejdź do Sundae','Szacunkowa płatność za subskrypcję','Wybierz plan Crew, aby zobaczyć szacunek.','Opcjonalny model planowania. Wyniki zależą od danych i działań.'],
  tr: ['Planınızı seçin','İhtiyaçlarınızı netleştirin','Tahmini inceleyin','Neye ihtiyacınız var?','Temel abonelik tahmini','USD · vergiler ve tek seferlik kurulum hariç','Fiyatınız nasıl hesaplanır','Tüm fiyat kademelerini görün','İsteğe bağlı. Ücret eklemeden eklenti önerir.','Portföyünüzü planlayalım.','250+ konum veya özel ihtiyaçlar için teklif hazırlıyoruz.','Tek tek Crew özelliklerini seçin','Tahminler dahil','Yapılandırma bağlantısını kopyala','Bağlantı kopyalandı','Bu bağlantı geçersiz veya kaldırılmış bir teklif içeriyor. Seçiminiz korundu.','Sundae’ye devam et','Abonelik ödeme tahmini','Tahmini görmek için bir Crew planı seçin.','İsteğe bağlı planlama modeli. Sonuçlar verilerinize ve eylemlerinize bağlıdır.'],
  ro: ['Alege planul','Ajustează nevoile','Verifică estimarea','De ce ai nevoie?','Estimarea abonamentului de bază','USD · fără taxe și implementare inițială','Cum se calculează prețul','Vezi toate tranșele de preț','Opțional. Recomandă extensii fără a adăuga costuri.','Să definim portofoliul tău.','Pentru 250+ locații sau cerințe speciale pregătim o ofertă.','Alege funcții Crew individuale','Prognoze incluse','Copiază linkul configurației','Link copiat','Linkul nu este valid sau folosește o ofertă retrasă. Selecția a fost păstrată.','Continuă către Sundae','Estimarea plății abonamentului','Alege un plan Crew pentru a vedea estimarea.','Model de planificare opțional. Rezultatele depind de date și acțiuni.'],
  sv: ['Välj plan','Förfina behoven','Granska uppskattningen','Vad behöver du?','Uppskattning av grundabonnemang','USD · skatter och engångsinstallation ingår inte','Så beräknas priset','Visa alla prisintervall','Valfritt. Rekommenderar tillägg utan att lägga till avgifter.','Låt oss planera din portfölj.','För 250+ platser eller särskilda behov tar vi fram ett förslag.','Välj enskilda Crew-funktioner','Prognoser ingår','Kopiera konfigurationslänk','Länk kopierad','Länken är ogiltig eller använder ett avslutat erbjudande. Ditt val har behållits.','Fortsätt till Sundae','Uppskattad abonnemangsbetalning','Välj en Crew-plan för att se uppskattningen.','Valfri planeringsmodell. Resultaten beror på dina data och åtgärder.'],
  'zh-Hans': ['选择方案','细化需求','查看估算','您需要什么？','基础订阅费用估算','美元 · 不含税费和一次性实施费','价格如何计算','查看完整阶梯价格','可选。仅推荐扩展功能，不自动增加费用。','为您的业务网络制定方案。','250 个以上地点或定制需求将单独报价。','选择单项 Crew 功能','包含预测功能','复制配置链接','链接已复制','此链接无效或使用已停售的产品。已保留您的选择。','继续前往 Sundae','订阅付款估算','请选择 Crew 方案以查看估算。','可选规划模型。结果取决于您的数据和行动。'],
  ja: ['プランを選ぶ','要件を調整','見積もりを確認','何が必要ですか？','基本サブスクリプションの概算','米ドル · 税金と初期設定費用は含まれません','価格の計算方法','すべての価格帯を表示','任意。追加機能を提案しますが、自動で料金は加算されません。','拠点全体の要件を整理しましょう。','250拠点以上または個別要件は別途ご提案します。','Crewの機能を個別に選ぶ','予測機能を含む','構成リンクをコピー','リンクをコピーしました','無効なリンク、または販売終了の製品です。現在の選択は保持されています。','Sundaeへ進む','サブスクリプション支払いの概算','Crewプランを選ぶと概算が表示されます。','任意の計画モデルです。結果はデータと行動により異なります。'],
  ko: ['플랜 선택','요구 사항 조정','예상 비용 확인','무엇이 필요하신가요?','기본 구독 예상 비용','미국 달러 · 세금 및 초기 설정 비용 제외','가격 계산 방식','전체 가격 구간 보기','선택 사항입니다. 확장 기능을 추천하며 요금을 자동으로 추가하지 않습니다.','사업장 전체 범위를 정해 보세요.','250개 이상의 사업장이나 맞춤 요구 사항은 별도로 제안합니다.','Crew 기능 개별 선택','예측 기능 포함','구성 링크 복사','링크 복사됨','유효하지 않거나 판매 종료된 상품의 링크입니다. 현재 선택을 유지했습니다.','Sundae로 계속','구독 결제 예상 금액','예상 비용을 보려면 Crew 플랜을 선택하세요.','선택적인 계획 모델입니다. 결과는 데이터와 실행에 따라 달라집니다.'],
  id: ['Pilih paket','Sesuaikan kebutuhan','Tinjau estimasi','Apa yang Anda butuhkan?','Estimasi langganan dasar','USD · pajak dan biaya penyiapan awal tidak termasuk','Cara harga dihitung','Lihat semua rentang harga','Opsional. Merekomendasikan tambahan tanpa menambahkan biaya.','Mari tentukan portofolio Anda.','Untuk 250+ lokasi atau kebutuhan khusus, kami menyiapkan proposal.','Pilih fitur Crew satu per satu','Prakiraan termasuk','Salin tautan konfigurasi','Tautan disalin','Tautan tidak valid atau menggunakan penawaran yang dihentikan. Pilihan Anda tetap tersimpan.','Lanjut ke Sundae','Estimasi pembayaran langganan','Pilih paket Crew untuk melihat estimasi.','Model perencanaan opsional. Hasil bergantung pada data dan tindakan Anda.'],
  vi: ['Chọn gói','Điều chỉnh nhu cầu','Xem ước tính','Bạn cần gì?','Ước tính gói đăng ký cơ bản','USD · chưa gồm thuế và phí triển khai ban đầu','Cách tính giá','Xem toàn bộ bậc giá','Tùy chọn. Đề xuất tiện ích mà không tự thêm phí.','Cùng xác định phạm vi hệ thống của bạn.','Từ 250 địa điểm hoặc nhu cầu riêng, chúng tôi sẽ lập đề xuất.','Chọn từng tính năng Crew','Bao gồm dự báo','Sao chép liên kết cấu hình','Đã sao chép liên kết','Liên kết không hợp lệ hoặc dùng sản phẩm đã ngừng bán. Lựa chọn hiện tại được giữ nguyên.','Tiếp tục đến Sundae','Ước tính thanh toán gói đăng ký','Chọn gói Crew để xem ước tính.','Mô hình lập kế hoạch tùy chọn. Kết quả phụ thuộc vào dữ liệu và hành động.'],
  ms: ['Pilih pelan','Perincikan keperluan','Semak anggaran','Apakah yang anda perlukan?','Anggaran langganan asas','USD · cukai dan persediaan awal tidak termasuk','Cara harga dikira','Lihat semua julat harga','Pilihan. Mengesyorkan tambahan tanpa menambah caj.','Mari tentukan portfolio anda.','Untuk 250+ lokasi atau keperluan khas, kami menyediakan cadangan.','Pilih fungsi Crew secara individu','Ramalan termasuk','Salin pautan konfigurasi','Pautan disalin','Pautan tidak sah atau menggunakan tawaran yang dihentikan. Pilihan anda dikekalkan.','Teruskan ke Sundae','Anggaran bayaran langganan','Pilih pelan Crew untuk melihat anggaran.','Model perancangan pilihan. Hasil bergantung pada data dan tindakan anda.'],
  hi: ['योजना चुनें','ज़रूरतें तय करें','अनुमान देखें','आपको क्या चाहिए?','मूल सदस्यता का अनुमान','अमेरिकी डॉलर · कर और एकमुश्त सेटअप शामिल नहीं','आपकी कीमत कैसे बनती है','पूरी मूल्य सूची देखें','वैकल्पिक। अतिरिक्त सुविधाओं की सलाह देता है, शुल्क अपने आप नहीं जोड़ता।','आपके कारोबार का दायरा तय करें।','250+ स्थानों या विशेष ज़रूरतों के लिए अलग प्रस्ताव तैयार करेंगे।','Crew सुविधाएँ अलग-अलग चुनें','पूर्वानुमान शामिल','कॉन्फ़िगरेशन लिंक कॉपी करें','लिंक कॉपी हुआ','यह लिंक अमान्य है या बंद की गई पेशकश का है। आपका चयन सुरक्षित है।','Sundae पर आगे बढ़ें','सदस्यता भुगतान का अनुमान','अनुमान देखने के लिए Crew योजना चुनें।','वैकल्पिक योजना मॉडल। परिणाम आपके डेटा और कदमों पर निर्भर हैं।'],
  ur: ['پلان منتخب کریں','ضروریات واضح کریں','تخمینہ دیکھیں','آپ کو کیا چاہیے؟','بنیادی سبسکرپشن کا تخمینہ','امریکی ڈالر · ٹیکس اور ابتدائی سیٹ اپ شامل نہیں','قیمت کیسے حساب ہوتی ہے','تمام قیمت کی سطحیں دیکھیں','اختیاری۔ اضافی سہولتیں تجویز کرتا ہے، خود کوئی فیس نہیں بڑھاتا۔','آپ کے کاروبار کا دائرہ طے کریں۔','250+ مقامات یا خصوصی ضروریات کے لیے الگ تجویز تیار کریں گے۔','Crew کی سہولتیں الگ منتخب کریں','پیش گوئی شامل','ترتیب کا لنک کاپی کریں','لنک کاپی ہو گیا','یہ لنک غلط ہے یا ختم شدہ پیشکش استعمال کرتا ہے۔ آپ کا انتخاب محفوظ ہے۔','Sundae پر آگے بڑھیں','سبسکرپشن کی ادائیگی کا تخمینہ','تخمینہ دیکھنے کے لیے Crew پلان منتخب کریں۔','اختیاری منصوبہ بندی کا ماڈل۔ نتائج آپ کے ڈیٹا اور اقدامات پر منحصر ہیں۔'],
  bn: ['প্ল্যান বেছে নিন','প্রয়োজন নির্দিষ্ট করুন','আনুমানিক খরচ দেখুন','আপনার কী প্রয়োজন?','মূল সাবস্ক্রিপশনের আনুমানিক খরচ','মার্কিন ডলার · কর ও প্রাথমিক সেটআপ বাদ','মূল্য কীভাবে গণনা হয়','সব মূল্যস্তর দেখুন','ঐচ্ছিক। বাড়তি সুবিধা প্রস্তাব করে, স্বয়ংক্রিয়ভাবে ফি যোগ করে না।','আপনার ব্যবসার পরিধি নির্ধারণ করি।','250+ অবস্থান বা বিশেষ চাহিদার জন্য আলাদা প্রস্তাব তৈরি করব।','Crew সুবিধা আলাদাভাবে বাছুন','পূর্বাভাস অন্তর্ভুক্ত','কনফিগারেশন লিংক কপি করুন','লিংক কপি হয়েছে','লিংকটি অবৈধ বা বন্ধ হওয়া অফার ব্যবহার করে। বর্তমান নির্বাচন রাখা হয়েছে।','Sundae-তে এগিয়ে যান','সাবস্ক্রিপশন পেমেন্টের আনুমানিক পরিমাণ','খরচ দেখতে একটি Crew প্ল্যান বেছে নিন।','ঐচ্ছিক পরিকল্পনা মডেল। ফলাফল আপনার ডেটা ও পদক্ষেপের ওপর নির্ভর করে।'],
  th: ['เลือกแผน','ปรับความต้องการ','ตรวจสอบประมาณการ','คุณต้องการอะไร?','ประมาณการค่าสมาชิกพื้นฐาน','ดอลลาร์สหรัฐ · ไม่รวมภาษีและค่าติดตั้งครั้งแรก','วิธีคำนวณราคา','ดูช่วงราคาทั้งหมด','ไม่บังคับ แนะนำส่วนเสริมโดยไม่เพิ่มค่าใช้จ่ายอัตโนมัติ','มาวางขอบเขตธุรกิจของคุณ','250 สาขาขึ้นไปหรือความต้องการเฉพาะจะจัดทำข้อเสนอแยก','เลือกฟังก์ชัน Crew รายการเดียว','รวมการคาดการณ์','คัดลอกลิงก์การตั้งค่า','คัดลอกลิงก์แล้ว','ลิงก์ไม่ถูกต้องหรือใช้งานข้อเสนอที่ยกเลิกแล้ว คงตัวเลือกปัจจุบันไว้','ไปต่อที่ Sundae','ประมาณการชำระค่าสมาชิก','เลือกแผน Crew เพื่อดูประมาณการ','แบบจำลองวางแผนที่ไม่บังคับ ผลลัพธ์ขึ้นอยู่กับข้อมูลและการดำเนินการของคุณ'],
};
export function getBuyerAuxiliaryActions(locale: keyof typeof buyerAuxiliaryCopy) {
  const row = actionRows[locale] ?? actionRows.de!;
  if (row.length !== actionKeys.length) throw new Error(`Incomplete buyer copy: ${locale}`);
  return Object.fromEntries(actionKeys.map((key, i) => [key, row[i]])) as Record<typeof actionKeys[number], string>;
}
