import type { PricingLocale } from './locales';

// Buying purposes, separate from the detailed product catalogue descriptions.
// Keep the four purposes in Foundation / Margin / Growth / Performance order.
export const buyerPlanCopy: Record<PricingLocale, { purposes: [string,string,string,string]; comparison: string }> = {
  en: { purposes: ['See your profit, staff costs and revenue in one place.','Understand food costs, reduce waste and manage supplier spending.','See which marketing, reservations and guest activity bring in business.','Bring cost and growth insights together, with forecasting included.'], comparison: 'Margin helps you control costs. Growth helps you attract and retain customers. Performance brings both together.' },
  ar: { purposes: ['شاهد الأرباح وتكاليف الموظفين والإيرادات في مكان واحد.','افهم تكاليف الطعام والهدر والإنفاق على الموردين.','اعرف كيف يساهم التسويق والحجوزات ونشاط الضيوف في أعمالك.','اجمع رؤى التكاليف والنمو، مع التنبؤ المشمول.'], comparison: 'تساعدك Margin على ضبط التكاليف، وتساعدك Growth على جذب العملاء والاحتفاظ بهم. تجمع Performance بينهما.' },
  fr: { purposes: ['Retrouvez bénéfices, coûts du personnel et revenus au même endroit.','Comprenez les coûts alimentaires, les pertes et les dépenses fournisseurs.','Identifiez le marketing, les réservations et les visites qui contribuent à votre activité.','Réunissez les analyses de coûts et de croissance, avec les prévisions incluses.'], comparison: 'Margin aide à maîtriser les coûts. Growth aide à attirer et fidéliser les clients. Performance réunit les deux.' },
  es: { purposes: ['Consulta beneficios, costes de personal e ingresos en un solo lugar.','Comprende los costes de alimentos, las mermas y el gasto en proveedores.','Descubre qué marketing, reservas y visitas contribuyen al negocio.','Combina el análisis de costes y crecimiento, con previsiones incluidas.'], comparison: 'Margin ayuda a controlar costes. Growth ayuda a atraer y retener clientes. Performance combina ambos.' },
  de: { purposes: ['Gewinn, Personalkosten und Umsatz an einem Ort sehen.','Lebensmittelkosten, Verschwendung und Lieferantenausgaben verstehen.','Erkennen, welches Marketing, welche Reservierungen und Gästebesuche zum Geschäft beitragen.','Kosten und Wachstum gemeinsam betrachten, inklusive Prognosen.'], comparison: 'Margin hilft bei der Kostenkontrolle. Growth hilft, Kunden zu gewinnen und zu halten. Performance verbindet beides.' },
  nl: { purposes: ['Bekijk winst, personeelskosten en omzet op één plek.','Begrijp voedselkosten, verspilling en uitgaven aan leveranciers.','Zie welke marketing, reserveringen en gastbezoeken bijdragen aan je bedrijf.','Combineer inzicht in kosten en groei, inclusief prognoses.'], comparison: 'Margin helpt kosten te beheersen. Growth helpt klanten aan te trekken en te behouden. Performance combineert beide.' },
  pt: { purposes: ['Veja lucro, custos de pessoal e receitas em um só lugar.','Entenda custos de alimentos, desperdício e gastos com fornecedores.','Veja quais ações de marketing, reservas e visitas contribuem para o negócio.','Combine análises de custos e crescimento, com previsões incluídas.'], comparison: 'Margin ajuda a controlar custos. Growth ajuda a atrair e reter clientes. Performance reúne os dois.' },
  hi: { purposes: ['लाभ, कर्मचारियों की लागत और आय एक जगह देखें।','खाद्य लागत, बर्बादी और आपूर्तिकर्ताओं पर खर्च समझें।','देखें कौन सा विपणन, बुकिंग और अतिथि गतिविधि व्यवसाय में योगदान देती है।','लागत और वृद्धि की जानकारी साथ देखें, पूर्वानुमान सहित।'], comparison: 'Margin लागत नियंत्रित करने में मदद करता है। Growth ग्राहक लाने और बनाए रखने में मदद करता है। Performance दोनों को जोड़ता है।' },
  ur: { purposes: ['منافع، عملے کی لاگت اور آمدنی ایک جگہ دیکھیں۔','خوراک کی لاگت، ضیاع اور سپلائرز پر خرچ سمجھیں۔','دیکھیں کون سی مارکیٹنگ، بکنگ اور مہمانوں کی سرگرمی کاروبار میں حصہ ڈالتی ہے۔','لاگت اور ترقی کی معلومات یکجا کریں، پیش گوئی سمیت۔'], comparison: 'Margin لاگت قابو کرنے میں مدد کرتا ہے۔ Growth گاہک لانے اور برقرار رکھنے میں مدد کرتا ہے۔ Performance دونوں کو یکجا کرتا ہے۔' },
  it: { purposes: ['Visualizza profitti, costi del personale e ricavi in un unico posto.','Comprendi costi alimentari, sprechi e spese per i fornitori.','Scopri quali attività di marketing, prenotazioni e visite contribuiscono al business.','Unisci analisi di costi e crescita, con previsioni incluse.'], comparison: 'Margin aiuta a controllare i costi. Growth aiuta ad attrarre e fidelizzare i clienti. Performance combina entrambi.' },
  pl: { purposes: ['Zobacz zysk, koszty personelu i przychody w jednym miejscu.','Poznaj koszty żywności, straty i wydatki na dostawców.','Sprawdź, które działania marketingowe, rezerwacje i wizyty wspierają biznes.','Połącz analizę kosztów i wzrostu z prognozami.'], comparison: 'Margin pomaga kontrolować koszty. Growth pomaga przyciągać i zatrzymywać klientów. Performance łączy oba obszary.' },
  tr: { purposes: ['Kâr, personel maliyetleri ve geliri tek yerde görün.','Gıda maliyetlerini, israfı ve tedarikçi harcamalarını anlayın.','Hangi pazarlama, rezervasyon ve misafir faaliyetlerinin işletmeye katkı sağladığını görün.','Maliyet ve büyüme analizlerini, tahminlerle birlikte bir araya getirin.'], comparison: 'Margin maliyetleri kontrol etmeye yardımcı olur. Growth müşteri çekmeye ve elde tutmaya yardımcı olur. Performance ikisini birleştirir.' },
  'zh-Hans': { purposes: ['在同一处查看利润、员工成本和收入。','了解食材成本、浪费和供应商支出。','了解哪些营销、预订和顾客活动为业务带来贡献。','结合成本和增长分析，包含预测功能。'], comparison: 'Margin 帮助控制成本。Growth 帮助吸引并留住顾客。Performance 结合两者。' },
  ja: { purposes: ['利益、人件費、売上を一か所で確認。','食材費、廃棄、仕入先への支出を把握。','どの販促、予約、来店が事業に貢献しているかを確認。','コストと成長の分析を統合。予測機能も含まれます。'], comparison: 'Margin はコスト管理を、Growth は集客と顧客の維持を支援します。Performance は両方をまとめます。' },
  ko: { purposes: ['이익, 인건비, 매출을 한곳에서 확인하세요.','식재료 비용, 낭비, 공급업체 지출을 파악하세요.','어떤 마케팅, 예약, 고객 활동이 사업에 기여하는지 확인하세요.','비용과 성장 분석을 함께 보고 예측 기능도 이용하세요.'], comparison: 'Margin은 비용 관리를 돕습니다. Growth는 고객 유치와 유지를 돕습니다. Performance는 두 가지를 결합합니다.' },
  id: { purposes: ['Lihat laba, biaya staf, dan pendapatan di satu tempat.','Pahami biaya makanan, pemborosan, dan pengeluaran pemasok.','Lihat pemasaran, reservasi, dan aktivitas tamu yang berkontribusi pada bisnis.','Gabungkan analisis biaya dan pertumbuhan, termasuk perkiraan.'], comparison: 'Margin membantu mengendalikan biaya. Growth membantu menarik dan mempertahankan pelanggan. Performance menggabungkan keduanya.' },
  vi: { purposes: ['Xem lợi nhuận, chi phí nhân viên và doanh thu ở một nơi.','Hiểu chi phí thực phẩm, lãng phí và chi tiêu cho nhà cung cấp.','Xem hoạt động tiếp thị, đặt bàn và khách hàng nào đóng góp cho kinh doanh.','Kết hợp phân tích chi phí và tăng trưởng, có dự báo đi kèm.'], comparison: 'Margin giúp kiểm soát chi phí. Growth giúp thu hút và giữ chân khách hàng. Performance kết hợp cả hai.' },
  ro: { purposes: ['Vezi profitul, costurile cu personalul și veniturile într-un singur loc.','Înțelege costurile alimentelor, risipa și cheltuielile cu furnizorii.','Vezi ce marketing, rezervări și vizite contribuie la afacere.','Combină analiza costurilor și a creșterii, cu previziuni incluse.'], comparison: 'Margin ajută la controlul costurilor. Growth ajută la atragerea și păstrarea clienților. Performance le combină.' },
  sv: { purposes: ['Se vinst, personalkostnader och intäkter på ett ställe.','Förstå råvarukostnader, svinn och leverantörsutgifter.','Se vilken marknadsföring, vilka bokningar och gästbesök som bidrar till verksamheten.','Kombinera kostnads- och tillväxtanalys, med prognoser inkluderade.'], comparison: 'Margin hjälper dig att kontrollera kostnader. Growth hjälper dig att locka och behålla kunder. Performance kombinerar båda.' },
  bn: { purposes: ['লাভ, কর্মীদের খরচ এবং আয় এক জায়গায় দেখুন।','খাবারের খরচ, অপচয় এবং সরবরাহকারীর ব্যয় বুঝুন।','কোন বিপণন, বুকিং এবং অতিথির কার্যকলাপ ব্যবসায় অবদান রাখছে দেখুন।','খরচ ও বৃদ্ধির বিশ্লেষণ একসঙ্গে দেখুন, পূর্বাভাসসহ।'], comparison: 'Margin খরচ নিয়ন্ত্রণে সাহায্য করে। Growth গ্রাহক আনা ও ধরে রাখতে সাহায্য করে। Performance দুটোকে এক করে।' },
  th: { purposes: ['ดูกำไร ค่าใช้จ่ายพนักงาน และรายได้ในที่เดียว','เข้าใจต้นทุนอาหาร ของเสีย และค่าใช้จ่ายผู้จัดส่ง','ดูว่าการตลาด การจอง และกิจกรรมลูกค้าใดช่วยธุรกิจ','รวมการวิเคราะห์ต้นทุนและการเติบโต พร้อมการคาดการณ์'], comparison: 'Margin ช่วยควบคุมต้นทุน Growth ช่วยดึงดูดและรักษาลูกค้า Performance รวมทั้งสองด้าน' },
  ms: { purposes: ['Lihat keuntungan, kos kakitangan dan hasil di satu tempat.','Fahami kos makanan, pembaziran dan perbelanjaan pembekal.','Lihat pemasaran, tempahan dan aktiviti tetamu yang menyumbang kepada perniagaan.','Gabungkan analisis kos dan pertumbuhan, termasuk ramalan.'], comparison: 'Margin membantu mengawal kos. Growth membantu menarik dan mengekalkan pelanggan. Performance menggabungkan kedua-duanya.' },
  az: { purposes: ['Mənfəəti, əməkdaş xərclərini və gəliri bir yerdə görün.','Qida xərclərini, israfı və təchizatçı ödənişlərini anlayın.','Hansı marketinq, rezervasiya və qonaq fəaliyyətinin işə fayda verdiyini görün.','Xərc və böyümə məlumatlarını proqnozla birlikdə birləşdirin.'], comparison: 'Margin xərclərə nəzarət edir. Growth müştəri cəlb etməyə və saxlamağa kömək edir. Performance hər ikisini birləşdirir.' },
  ru: { purposes: ['Видите прибыль, расходы на персонал и выручку в одном месте.','Понимайте расходы на продукты, потери и затраты поставщиков.','Видите, какие маркетинг, бронирования и действия гостей приносят результат.','Объединяйте анализ расходов и роста с прогнозированием.'], comparison: 'Margin помогает контролировать расходы. Growth помогает привлекать и удерживать клиентов. Performance объединяет оба направления.' },
  pap: { purposes: ['Mira ganashi, gastunan di personal i entrada den un luga.','Komprondé gastunan di kuminda, desperdicio i gastunan di suplidornan.','Mira kua marketin, reservashon i aktividat di bishitante ta yuda bo negoshi.','Hunta analisis di kosto i kresementu ku predikshonnan inkluí.'], comparison: 'Margin ta yuda kontrolá kosto. Growth ta yuda trese i retené kliente. Performance ta huntu tur dos.' },
};
