import type { PricingLocale } from './locales';

// Buyer benefits, rather than internal module definitions. No outcome guarantees.
export const englishFeatureHelp = {
  profit: 'See which locations are making money and what is reducing profit, so you know where to act first.',
  labor: 'Compare staff costs with sales and spot overtime or staffing gaps, so you can put the right team on each shift.',
  revenue: 'Spot unusual discounts, voids and missing sales, so you can investigate where revenue is slipping away.',
  pulse: 'Keep an eye on sales, staffing and service as the day unfolds, so you can respond before a small issue grows.',
  inventory: 'See what ingredients really cost, where stock is being wasted and which dishes earn their keep.',
  purchasing: 'Compare supplier prices and track unexpected increases, so you know where to challenge costs or negotiate.',
  marketing: 'Connect campaign spending with sales and customer activity, so you can see which channels deserve your budget.',
  reservations: 'See booking patterns, cancellations and no-shows, so you can plan staffing and make better use of your tables.',
  delivery: 'Compare delivery channels after commissions and fees, so you can see what each order really earns.',
  guest: 'Bring guest reviews and feedback together to see what customers value and what needs fixing.',
  guest_crm: 'Understand who returns, who is drifting away and which guest groups to focus on, so you can plan more relevant offers.',
  foresight_action: 'Forecast sales and costs, compare what-if plans and turn the findings into actions. Plan ahead with a clearer view of the trade-offs.',
  crew_lite: 'Give a small team one place for basic schedules, time-off requests and their own documents.',
  crew_scheduling: 'Build shifts around availability and demand, handle swaps and keep everyone clear on when they are working.',
  crew_operations: 'Keep employee records, documents, onboarding and team requests together. Includes scheduling, so managers spend less time chasing admin.',
  crew_tna: 'Review clock-ins, breaks and worked hours, so you can resolve missing time before preparing payroll.',
  crew_payroll: 'Bring approved hours and pay information together for payroll, payslips or a handoff to your provider. Country support is confirmed before setup.',
  crew_people_intelligence: 'See patterns in staff performance, retention and skills, so you can decide where coaching, hiring or training will help.',
  concept_franchise: 'Compare franchise locations, review royalties and spot where operators need support across your network.',
  concept_hotel_fb: 'See the profit picture for hotel restaurants, bars, banquets and room service, so you know which outlets need attention.',
  concept_cloud_kitchen: 'Compare delivery brands sharing a kitchen and see how commissions and kitchen costs affect what each one earns.',
  concept_catering: 'Compare the price quoted with the actual cost of an event, so you can protect the margin on your next booking. Scope is confirmed separately.',
  concept_production: 'Track batch costs, ingredient use and output from a central kitchen, so you can find waste and understand production margins. Scope is confirmed separately.',
  concept_rental_commissary: 'See how rented kitchen space is used and what each tenant contributes, so you can review occupancy and charges.',
  competitive: 'Track nearby competitors’ menus, prices, promotions and reviews, so you can make informed decisions about your own offer.',
  events: 'See local events and other demand signals, so you can prepare staffing and stock for busier or quieter days.',
  trends: 'Follow changes in local demand and food preferences, so you can judge where your menu or growth plans may need to adapt.',
  bundle: 'Bring competitor changes, local events and market trends into one view, so your plans reflect what is happening around each location.',
  cross_pro: 'Explore connections between sales, staffing, stock and marketing. See what moves together and where to investigate before changing your plan.',
} as const;
export type FeatureHelpId = keyof typeof englishFeatureHelp;

// Existing catalogue translations cover the older Core and Watchtower features.
// These translations cover the feature families absent from that catalogue copy.
const extraIds = ['guest_crm', 'foresight_action', 'crew_lite', 'crew_scheduling', 'crew_operations', 'crew_tna', 'crew_payroll', 'crew_people_intelligence', 'concept_franchise', 'concept_hotel_fb', 'concept_cloud_kitchen', 'concept_catering', 'concept_production', 'concept_rental_commissary'] as const;
export const featureHelpExtras: Record<Exclude<PricingLocale, 'en'>, readonly string[]> = {
  ar: ['اعرف من يعود من الضيوف ومن يقلّ تردده لتخطط لعروض أكثر ملاءمة.', 'توقّع المبيعات والتكاليف وقارن الخطط قبل تحويل النتائج إلى إجراءات.', 'جداول أساسية وطلبات إجازة ومستندات الفريق الصغير في مكان واحد.', 'نظّم الورديات حسب التوفر والطلب، وأدر التبديلات ليعرف الجميع مواعيد عملهم.', 'اجمع سجلات الموظفين والمستندات وتهيئة الموظفين والطلبات. يشمل جدولة الورديات.', 'راجع الحضور والاستراحات وساعات العمل لحل الوقت الناقص قبل إعداد الرواتب.', 'اجمع الساعات المعتمدة وبيانات الأجر لإعداد الرواتب أو تسليمها لمزودك. يُؤكّد دعم البلد قبل الإعداد.', 'اعرف أنماط أداء الموظفين واستبقائهم ومهاراتهم لتحدد أولويات التدريب والتوظيف.', 'قارن مواقع الامتياز وراجع رسوم الامتياز لتعرف من يحتاج إلى دعم.', 'اعرف ربحية مطاعم الفندق وحاناته ومآدبه وخدمة الغرف لتحدد ما يحتاج إلى تحسين.', 'قارن علامات التوصيل في مطبخ مشترك واعرف أثر العمولات وتكاليف المطبخ على الأرباح.', 'قارن سعر الفعالية المتفق عليه بتكلفتها الفعلية لحماية هامش الربح. يُؤكّد النطاق بشكل منفصل.', 'تابع تكلفة الدفعات واستخدام المكونات والإنتاج لتكتشف الهدر. يُؤكّد النطاق بشكل منفصل.', 'راجع استخدام مساحة المطبخ المؤجرة ومساهمة كل مستأجر لتقيّم الإشغال والرسوم.'],
  fr: ['Identifiez les clients fidèles et ceux qui reviennent moins pour préparer des offres plus pertinentes.', 'Prévoyez ventes et coûts, comparez des scénarios et passez des constats aux actions.', 'Réunissez plannings simples, demandes de congés et documents d’une petite équipe.', 'Planifiez selon les disponibilités et la demande, gérez les échanges et informez chacun de ses horaires.', 'Centralisez dossiers, documents, arrivée des salariés et demandes. La planification est incluse.', 'Vérifiez pointages, pauses et heures travaillées avant de préparer la paie.', 'Réunissez heures validées et rémunérations pour la paie ou votre prestataire. La prise en charge du pays est confirmée avant la mise en place.', 'Repérez les tendances de performance, de fidélisation et de compétences pour cibler formation et recrutement.', 'Comparez les sites franchisés et suivez les redevances pour identifier les besoins d’accompagnement.', 'Suivez la rentabilité des restaurants, bars, banquets et du service en chambre de votre hôtel.', 'Comparez les marques de livraison d’une cuisine partagée et l’effet des commissions sur leurs marges.', 'Comparez le devis au coût réel d’un événement pour préserver la marge du suivant. Le périmètre est confirmé séparément.', 'Suivez coûts par lot, ingrédients et production pour repérer le gaspillage. Le périmètre est confirmé séparément.', 'Suivez l’utilisation des espaces de cuisine loués et la contribution de chaque locataire.'],
  es: ['Identifica quién vuelve y quién está dejando de venir para preparar ofertas más relevantes.', 'Prevé ventas y costes, compara escenarios y convierte los hallazgos en acciones.', 'Reúne horarios básicos, solicitudes de vacaciones y documentos de un equipo pequeño.', 'Planifica según disponibilidad y demanda, gestiona cambios e informa a cada persona de sus turnos.', 'Reúne expedientes, documentos, incorporaciones y solicitudes. Incluye la planificación de turnos.', 'Revisa fichajes, descansos y horas trabajadas antes de preparar la nómina.', 'Reúne horas aprobadas y datos salariales para la nómina o tu proveedor. La cobertura del país se confirma antes de la puesta en marcha.', 'Detecta patrones de rendimiento, retención y habilidades para orientar formación y contratación.', 'Compara locales franquiciados y revisa regalías para identificar dónde hace falta apoyo.', 'Consulta la rentabilidad de restaurantes, bares, banquetes y servicio de habitaciones del hotel.', 'Compara marcas de reparto en una cocina compartida y el efecto de las comisiones sobre sus márgenes.', 'Compara el presupuesto con el coste real del evento para proteger el margen del siguiente. El alcance se confirma por separado.', 'Sigue costes por lote, ingredientes y producción para detectar desperdicio. El alcance se confirma por separado.', 'Revisa el uso de las cocinas alquiladas y la aportación de cada inquilino.'],
  de: ['Erkennen Sie, welche Gäste wiederkommen und welche seltener kommen, um passende Angebote zu planen.', 'Prognostizieren Sie Umsatz und Kosten, vergleichen Sie Szenarien und leiten Sie Maßnahmen ab.', 'Einfache Dienstpläne, Urlaubsanträge und Dokumente für ein kleines Team an einem Ort.', 'Planen Sie Schichten nach Verfügbarkeit und Nachfrage und verwalten Sie Schichtwechsel.', 'Bündeln Sie Personalakten, Dokumente, Einarbeitung und Anfragen. Dienstplanung ist enthalten.', 'Prüfen Sie Stempelzeiten, Pausen und Arbeitsstunden vor der Lohnvorbereitung.', 'Bündeln Sie bestätigte Stunden und Lohndaten für die Abrechnung oder Ihren Anbieter. Die Länderunterstützung wird vor der Einrichtung bestätigt.', 'Erkennen Sie Muster bei Leistung, Bindung und Fähigkeiten, um Schulung und Einstellung zu planen.', 'Vergleichen Sie Franchise-Standorte und prüfen Sie Lizenzgebühren, um Unterstützungsbedarf zu erkennen.', 'Prüfen Sie die Rentabilität von Hotelrestaurants, Bars, Banketten und Zimmerservice.', 'Vergleichen Sie Liefermarken einer gemeinsamen Küche und die Wirkung von Provisionen auf den Gewinn.', 'Vergleichen Sie Angebot und tatsächliche Veranstaltungskosten. Der Umfang wird separat bestätigt.', 'Verfolgen Sie Chargenkosten, Zutaten und Produktion, um Verschwendung zu finden. Der Umfang wird separat bestätigt.', 'Prüfen Sie die Nutzung vermieteter Küchenflächen und den Beitrag jedes Mieters.'],
  nl: ['Zie welke gasten terugkomen en welke minder vaak komen om relevantere aanbiedingen te plannen.', 'Voorspel omzet en kosten, vergelijk plannen en zet inzichten om in acties.', 'Eenvoudige roosters, verlofaanvragen en documenten voor een klein team op één plek.', 'Plan diensten op basis van beschikbaarheid en vraag en regel dienstwissels.', 'Bundel personeelsdossiers, documenten, onboarding en verzoeken. Roosters zijn inbegrepen.', 'Controleer inklokken, pauzes en gewerkte uren voordat je de loonadministratie voorbereidt.', 'Bundel goedgekeurde uren en loongegevens voor de loonadministratie of je aanbieder. Landondersteuning wordt vóór de inrichting bevestigd.', 'Zie patronen in prestaties, behoud en vaardigheden om opleiding en werving te richten.', 'Vergelijk franchiselocaties en royalty’s om te zien waar ondersteuning nodig is.', 'Bekijk de winstgevendheid van hotelrestaurants, bars, banketten en roomservice.', 'Vergelijk bezorgmerken in een gedeelde keuken en de invloed van commissies op hun winst.', 'Vergelijk de offerte met de werkelijke evenementkosten. De omvang wordt apart bevestigd.', 'Volg batchkosten, ingrediënten en productie om verspilling te vinden. De omvang wordt apart bevestigd.', 'Bekijk het gebruik van verhuurde keukenruimte en de bijdrage van elke huurder.'],
  pt: ['Veja quais clientes voltam e quais estão vindo menos para planejar ofertas mais relevantes.', 'Preveja vendas e custos, compare cenários e transforme as conclusões em ações.', 'Escalas básicas, pedidos de férias e documentos de uma equipe pequena em um só lugar.', 'Planeje turnos conforme disponibilidade e demanda e organize trocas.', 'Reúna registros, documentos, integração de funcionários e solicitações. Inclui escalas.', 'Revise registros de ponto, pausas e horas trabalhadas antes de preparar a folha.', 'Reúna horas aprovadas e dados salariais para a folha ou seu fornecedor. O suporte ao país é confirmado antes da configuração.', 'Veja padrões de desempenho, retenção e habilidades para orientar treinamento e contratação.', 'Compare unidades franqueadas e royalties para identificar onde é preciso apoio.', 'Veja a rentabilidade dos restaurantes, bares, banquetes e serviço de quarto do hotel.', 'Compare marcas de entrega em uma cozinha compartilhada e o efeito das comissões sobre o lucro.', 'Compare o orçamento com o custo real do evento. O escopo é confirmado separadamente.', 'Acompanhe custos por lote, ingredientes e produção para encontrar desperdício. O escopo é confirmado separadamente.', 'Revise o uso de cozinhas alugadas e a contribuição de cada locatário.'],
  hi: ['देखें कौन से मेहमान लौटते हैं और कौन कम आने लगे हैं, ताकि प्रासंगिक ऑफ़र बना सकें।', 'बिक्री और लागत का अनुमान लगाएँ, योजनाएँ तुलना करें और निष्कर्षों पर कार्रवाई करें।', 'छोटी टीम के शेड्यूल, छुट्टी के अनुरोध और दस्तावेज़ एक जगह रखें।', 'उपलब्धता और मांग के अनुसार शिफ़्ट बनाएँ और बदलाव संभालें।', 'कर्मचारी रिकॉर्ड, दस्तावेज़, नए कर्मचारियों की शुरुआत और अनुरोध एक जगह रखें। शेड्यूलिंग शामिल है।', 'वेतन तैयार करने से पहले उपस्थिति, ब्रेक और काम के घंटे जाँचें।', 'स्वीकृत घंटे और वेतन जानकारी पेरोल या अपने प्रदाता के लिए जोड़ें। सेटअप से पहले देश का समर्थन पुष्ट किया जाता है।', 'प्रदर्शन, कर्मचारियों के टिके रहने और कौशल के रुझान देखकर प्रशिक्षण और भर्ती तय करें।', 'फ्रैंचाइज़ी स्थानों और रॉयल्टी की तुलना करके सहायता की ज़रूरत पहचानें।', 'होटल रेस्तराँ, बार, बैंक्वेट और रूम सर्विस का लाभ देखें।', 'साझा रसोई के डिलीवरी ब्रांड और कमीशन का लाभ पर असर तुलना करें।', 'कार्यक्रम के अनुमानित और वास्तविक खर्च की तुलना करें। दायरा अलग से पुष्ट किया जाता है।', 'बैच लागत, सामग्री और उत्पादन देखकर बर्बादी पहचानें। दायरा अलग से पुष्ट किया जाता है।', 'किराए की रसोई का उपयोग और हर किरायेदार का योगदान देखें।'],
  ur: ['دیکھیں کون سے مہمان واپس آتے ہیں اور کون کم آنے لگے ہیں، تاکہ موزوں پیشکشیں بنا سکیں۔', 'فروخت اور لاگت کی پیش گوئی کریں، منصوبوں کا موازنہ کریں اور نتائج پر عمل کریں۔', 'چھوٹی ٹیم کے شیڈول، چھٹی کی درخواستیں اور دستاویزات ایک جگہ رکھیں۔', 'دستیابی اور طلب کے مطابق شفٹیں بنائیں اور تبدیلیاں سنبھالیں۔', 'ملازمین کے ریکارڈ، دستاویزات، شمولیت اور درخواستیں یکجا کریں۔ شیڈولنگ شامل ہے۔', 'تنخواہ تیار کرنے سے پہلے حاضری، وقفے اور کام کے گھنٹے دیکھیں۔', 'منظور شدہ گھنٹے اور تنخواہ کی معلومات پے رول یا اپنے فراہم کنندہ کے لیے جمع کریں۔ سیٹ اپ سے پہلے ملک کی معاونت کی تصدیق ہوتی ہے۔', 'کارکردگی، ملازمین کے برقرار رہنے اور مہارتوں کے رجحانات دیکھ کر تربیت اور بھرتی کا فیصلہ کریں۔', 'فرنچائز مقامات اور رائلٹی کا موازنہ کر کے مدد کی ضرورت پہچانیں۔', 'ہوٹل کے ریستوران، بار، ضیافت اور روم سروس کا منافع دیکھیں۔', 'مشترکہ کچن کے ڈیلیوری برانڈز اور کمیشن کے منافع پر اثر کا موازنہ کریں۔', 'تقریب کے تخمینے اور اصل لاگت کا موازنہ کریں۔ دائرہ الگ سے طے ہوتا ہے۔', 'بیچ کی لاگت، اجزا اور پیداوار سے ضیاع پہچانیں۔ دائرہ الگ سے طے ہوتا ہے۔', 'کرائے کے کچن کا استعمال اور ہر کرایہ دار کا حصہ دیکھیں۔'],
  it: ['Scopri chi ritorna e chi viene meno spesso per preparare offerte più pertinenti.', 'Prevedi vendite e costi, confronta scenari e trasforma i risultati in azioni.', 'Riunisci turni semplici, richieste di ferie e documenti di una piccola squadra.', 'Pianifica secondo disponibilità e domanda e gestisci gli scambi di turno.', 'Riunisci fascicoli, documenti, inserimento e richieste. Include la pianificazione dei turni.', 'Controlla timbrature, pause e ore lavorate prima di preparare le paghe.', 'Riunisci ore approvate e dati retributivi per le paghe o il tuo fornitore. Il supporto del paese è confermato prima della configurazione.', 'Individua tendenze di rendimento, permanenza e competenze per orientare formazione e assunzioni.', 'Confronta sedi in franchising e royalty per individuare chi ha bisogno di supporto.', 'Controlla la redditività di ristoranti, bar, banchetti e servizio in camera dell’hotel.', 'Confronta marchi di consegna in una cucina condivisa e l’effetto delle commissioni sui margini.', 'Confronta preventivo e costo reale dell’evento. L’ambito è confermato separatamente.', 'Segui costi per lotto, ingredienti e produzione per trovare sprechi. L’ambito è confermato separatamente.', 'Controlla l’uso degli spazi cucina affittati e il contributo di ogni inquilino.'],
  pl: ['Zobacz, którzy goście wracają, a którzy bywają rzadziej, by przygotować trafniejsze oferty.', 'Prognozuj sprzedaż i koszty, porównuj scenariusze i przekładaj wnioski na działania.', 'Proste grafiki, wnioski urlopowe i dokumenty małego zespołu w jednym miejscu.', 'Planuj zmiany według dostępności i popytu oraz obsługuj zamiany.', 'Połącz akta, dokumenty, wdrażanie pracowników i wnioski. Obejmuje planowanie zmian.', 'Sprawdź wejścia, przerwy i godziny pracy przed przygotowaniem płac.', 'Zbierz zatwierdzone godziny i dane płacowe dla listy płac lub dostawcy. Obsługa kraju jest potwierdzana przed konfiguracją.', 'Znajdź wzorce wyników, utrzymania pracowników i umiejętności, by zaplanować szkolenia i rekrutację.', 'Porównuj lokale franczyzowe i opłaty, by wskazać potrzeby wsparcia.', 'Zobacz rentowność hotelowych restauracji, barów, bankietów i obsługi pokojowej.', 'Porównuj marki dostawcze we wspólnej kuchni i wpływ prowizji na zysk.', 'Porównaj wycenę z rzeczywistym kosztem wydarzenia. Zakres jest potwierdzany osobno.', 'Śledź koszty partii, składniki i produkcję, by znaleźć straty. Zakres jest potwierdzany osobno.', 'Sprawdź wykorzystanie wynajmowanych kuchni i wkład każdego najemcy.'],
  tr: ['Kimlerin geri geldiğini ve kimlerin daha seyrek geldiğini görerek uygun teklifler planlayın.', 'Satış ve maliyetleri tahmin edin, senaryoları karşılaştırın ve bulguları eyleme dönüştürün.', 'Küçük bir ekibin temel vardiyaları, izin talepleri ve belgeleri tek yerde.', 'Uygunluk ve talebe göre vardiya planlayın, değişimleri yönetin.', 'Personel kayıtlarını, belgeleri, işe başlangıcı ve talepleri birleştirin. Vardiya planlama dahildir.', 'Bordro hazırlamadan önce girişleri, molaları ve çalışma saatlerini kontrol edin.', 'Onaylı saatleri ve ücret bilgilerini bordro veya sağlayıcınız için birleştirin. Ülke desteği kurulumdan önce doğrulanır.', 'Eğitim ve işe alım için performans, çalışan bağlılığı ve beceri eğilimlerini görün.', 'Destek ihtiyacını görmek için franchise şubelerini ve telif ücretlerini karşılaştırın.', 'Otel restoranları, barları, ziyafetleri ve oda servisinin kârlılığını görün.', 'Ortak mutfaktaki teslimat markalarını ve komisyonların kâra etkisini karşılaştırın.', 'Etkinlik teklifini gerçek maliyetle karşılaştırın. Kapsam ayrıca doğrulanır.', 'İsrafı bulmak için parti maliyetleri, malzemeler ve üretimi izleyin. Kapsam ayrıca doğrulanır.', 'Kiralanan mutfakların kullanımını ve her kiracının katkısını görün.'],
  'zh-Hans': ['了解哪些顾客会再次光顾，哪些正在流失，以便制定更合适的优惠。', '预测销售和成本，比较不同方案，并将发现转化为行动。', '把小团队的基本排班、请假申请和文件放在一起。', '根据人员可用时间和需求安排班次，并处理换班。', '集中管理员工档案、文件、入职和申请。包含排班。', '核对打卡、休息和工时，在准备工资前解决遗漏。', '汇总已批准的工时和薪资信息，用于工资处理或交给服务商。设置前确认国家支持情况。', '查看员工表现、留任和技能的变化，帮助安排培训和招聘。', '比较加盟门店和特许经营费用，找出需要支持的门店。', '查看酒店餐厅、酒吧、宴会和客房餐饮的盈利情况。', '比较共用厨房的外卖品牌，以及佣金对利润的影响。', '比较活动报价与实际成本。服务范围另行确认。', '追踪批次成本、原料使用和产出，找出浪费。服务范围另行确认。', '查看出租厨房的使用情况和各租户的贡献。'],
  ja: ['再来店するお客様と来店が減ったお客様を把握し、適切な提案を考えます。', '売上と費用を予測し、複数の計画を比較して行動につなげます。', '小規模チームの基本シフト、休暇申請、書類を一か所にまとめます。', '勤務可能時間と需要に合わせてシフトを組み、交代を管理します。', '従業員記録、書類、入社手続き、申請をまとめます。シフト管理を含みます。', '給与準備の前に打刻、休憩、労働時間を確認します。', '承認済み時間と給与情報を給与処理や委託先への引き継ぎにまとめます。対応国は設定前に確認します。', '実績、定着、スキルの傾向から研修や採用の優先順位を考えます。', '加盟店とロイヤルティを比較し、支援が必要な店舗を把握します。', 'ホテルのレストラン、バー、宴会、ルームサービスの収益性を確認します。', '共有厨房のデリバリーブランドと手数料が利益に与える影響を比較します。', 'イベント見積もりと実際の費用を比較します。対象範囲は別途確認します。', 'バッチ費用、食材、生産量を追跡し、無駄を見つけます。対象範囲は別途確認します。', '貸し厨房の利用状況と各テナントの貢献を確認します。'],
  ko: ['재방문 고객과 방문이 줄어든 고객을 파악해 더 적절한 혜택을 계획하세요.', '매출과 비용을 예측하고 계획을 비교해 결과를 실행으로 옮기세요.', '소규모 팀의 기본 근무표, 휴가 신청과 서류를 한곳에 모으세요.', '가용 시간과 수요에 맞춰 근무를 계획하고 교대를 관리하세요.', '직원 기록, 서류, 입사 절차와 요청을 모으세요. 근무표 관리가 포함됩니다.', '급여 준비 전에 출퇴근, 휴식과 근무 시간을 확인하세요.', '승인된 시간과 급여 정보를 급여 처리나 서비스 제공업체 전달용으로 모으세요. 국가 지원은 설정 전에 확인합니다.', '성과, 직원 유지와 기술의 패턴을 보고 교육과 채용을 계획하세요.', '가맹점과 로열티를 비교해 지원이 필요한 곳을 찾으세요.', '호텔 식당, 바, 연회와 룸서비스의 수익성을 확인하세요.', '공유 주방의 배달 브랜드와 수수료가 수익에 미치는 영향을 비교하세요.', '행사 견적과 실제 비용을 비교하세요. 범위는 별도로 확인합니다.', '배치 비용, 식재료와 생산량을 추적해 낭비를 찾으세요. 범위는 별도로 확인합니다.', '임대 주방의 이용률과 각 임차인의 기여를 확인하세요.'],
  id: ['Lihat tamu yang kembali dan yang makin jarang datang untuk merencanakan penawaran yang lebih sesuai.', 'Perkirakan penjualan dan biaya, bandingkan rencana, lalu ubah temuan menjadi tindakan.', 'Jadwal dasar, permintaan cuti dan dokumen tim kecil di satu tempat.', 'Susun giliran kerja sesuai ketersediaan dan permintaan serta kelola pertukaran.', 'Satukan catatan karyawan, dokumen, orientasi dan permintaan. Penjadwalan termasuk.', 'Periksa absensi, istirahat dan jam kerja sebelum menyiapkan penggajian.', 'Satukan jam yang disetujui dan informasi upah untuk penggajian atau penyedia Anda. Dukungan negara dikonfirmasi sebelum penyiapan.', 'Lihat pola kinerja, retensi dan keterampilan untuk menentukan pelatihan dan perekrutan.', 'Bandingkan lokasi waralaba dan royalti untuk mengetahui kebutuhan dukungan.', 'Lihat laba restoran, bar, jamuan dan layanan kamar hotel.', 'Bandingkan merek pengantaran di dapur bersama dan dampak komisi pada laba.', 'Bandingkan penawaran dengan biaya acara sebenarnya. Cakupan dikonfirmasi terpisah.', 'Pantau biaya per batch, bahan dan hasil produksi untuk menemukan pemborosan. Cakupan dikonfirmasi terpisah.', 'Tinjau penggunaan dapur sewaan dan kontribusi setiap penyewa.'],
  vi: ['Xem khách nào quay lại và khách nào đến ít hơn để lên ưu đãi phù hợp.', 'Dự báo doanh thu và chi phí, so sánh phương án rồi chuyển kết quả thành hành động.', 'Lịch làm cơ bản, yêu cầu nghỉ phép và tài liệu của nhóm nhỏ ở một nơi.', 'Xếp ca theo thời gian sẵn có và nhu cầu, quản lý đổi ca.', 'Tập hợp hồ sơ nhân viên, tài liệu, tiếp nhận nhân viên và yêu cầu. Bao gồm xếp ca.', 'Kiểm tra chấm công, giờ nghỉ và giờ làm trước khi chuẩn bị bảng lương.', 'Tập hợp giờ đã duyệt và thông tin lương để xử lý lương hoặc bàn giao cho nhà cung cấp. Hỗ trợ quốc gia được xác nhận trước khi thiết lập.', 'Xem xu hướng hiệu suất, giữ chân và kỹ năng để định hướng đào tạo và tuyển dụng.', 'So sánh cơ sở nhượng quyền và phí để tìm nơi cần hỗ trợ.', 'Xem lợi nhuận nhà hàng, quầy bar, tiệc và dịch vụ phòng của khách sạn.', 'So sánh thương hiệu giao đồ ăn trong bếp chung và tác động của hoa hồng lên lợi nhuận.', 'So sánh báo giá với chi phí thực tế của sự kiện. Phạm vi được xác nhận riêng.', 'Theo dõi chi phí từng mẻ, nguyên liệu và sản lượng để tìm lãng phí. Phạm vi được xác nhận riêng.', 'Xem mức sử dụng bếp cho thuê và đóng góp của từng bên thuê.'],
  ro: ['Aflați cine revine și cine vine mai rar pentru a pregăti oferte mai potrivite.', 'Estimați vânzările și costurile, comparați planuri și transformați concluziile în acțiuni.', 'Programări simple, cereri de concediu și documentele unei echipe mici într-un singur loc.', 'Planificați ture după disponibilitate și cerere și gestionați schimburile.', 'Reuniți dosare, documente, integrarea angajaților și cereri. Include planificarea turelor.', 'Verificați pontajele, pauzele și orele lucrate înainte de pregătirea salariilor.', 'Reuniți orele aprobate și datele salariale pentru plată sau furnizor. Suportul țării este confirmat înainte de configurare.', 'Observați tipare de performanță, retenție și competențe pentru formare și recrutare.', 'Comparați locațiile în franciză și redevențele pentru a identifica nevoile de sprijin.', 'Vedeți profitabilitatea restaurantelor, barurilor, banchetelor și serviciului de cameră din hotel.', 'Comparați mărcile de livrare dintr-o bucătărie comună și impactul comisioanelor asupra profitului.', 'Comparați oferta cu costul real al evenimentului. Domeniul este confirmat separat.', 'Urmăriți costurile pe lot, ingredientele și producția pentru a găsi risipa. Domeniul este confirmat separat.', 'Verificați utilizarea bucătăriilor închiriate și contribuția fiecărui chiriaș.'],
  sv: ['Se vilka gäster som återkommer och vilka som kommer mer sällan för att planera relevanta erbjudanden.', 'Prognostisera försäljning och kostnader, jämför planer och omsätt resultat i åtgärder.', 'Enkla scheman, ledighetsansökningar och dokument för ett litet team på ett ställe.', 'Planera pass efter tillgänglighet och efterfrågan och hantera byten.', 'Samla personalregister, dokument, introduktion och förfrågningar. Schemaläggning ingår.', 'Granska instämplingar, raster och arbetstimmar före löneförberedelsen.', 'Samla godkända timmar och löneuppgifter för lön eller din leverantör. Landstöd bekräftas före införandet.', 'Se mönster i prestation, personalbehållning och kompetens för att planera utbildning och rekrytering.', 'Jämför franchiseställen och avgifter för att se var stöd behövs.', 'Se lönsamheten för hotellets restauranger, barer, banketter och rumsservice.', 'Jämför leveransvarumärken i ett delat kök och provisionernas påverkan på vinsten.', 'Jämför offert med faktisk evenemangskostnad. Omfattningen bekräftas separat.', 'Följ batchkostnader, råvaror och produktion för att hitta svinn. Omfattningen bekräftas separat.', 'Granska användningen av uthyrda kök och varje hyresgästs bidrag.'],
  bn: ['কোন অতিথি ফিরছেন আর কার আসা কমছে তা দেখে উপযুক্ত অফার পরিকল্পনা করুন।', 'বিক্রি ও খরচের পূর্বাভাস দিন, পরিকল্পনা তুলনা করুন এবং ফলাফলের ভিত্তিতে পদক্ষেপ নিন।', 'ছোট দলের সাধারণ শিফট, ছুটির আবেদন ও নথি এক জায়গায় রাখুন।', 'সময় ও চাহিদা অনুযায়ী শিফট তৈরি করুন এবং বদল পরিচালনা করুন।', 'কর্মীর রেকর্ড, নথি, যোগদান ও অনুরোধ একত্র করুন। শিফট পরিকল্পনা অন্তর্ভুক্ত।', 'বেতন প্রস্তুতির আগে উপস্থিতি, বিরতি ও কাজের সময় দেখুন।', 'বেতন বা আপনার সরবরাহকারীর জন্য অনুমোদিত সময় ও বেতনের তথ্য একত্র করুন। সেটআপের আগে দেশের সমর্থন নিশ্চিত করা হয়।', 'কর্মদক্ষতা, কর্মী ধরে রাখা ও দক্ষতার ধারা দেখে প্রশিক্ষণ ও নিয়োগ ঠিক করুন।', 'সহায়তার প্রয়োজন বুঝতে ফ্র্যাঞ্চাইজি স্থান ও রয়্যালটি তুলনা করুন।', 'হোটেলের রেস্তোরাঁ, বার, ভোজ ও রুম সার্ভিসের লাভ দেখুন।', 'একই রান্নাঘরের ডেলিভারি ব্র্যান্ড ও কমিশনের লাভের ওপর প্রভাব তুলনা করুন।', 'অনুষ্ঠানের প্রস্তাবিত মূল্য ও প্রকৃত খরচ তুলনা করুন। পরিধি আলাদাভাবে নিশ্চিত হয়।', 'অপচয় খুঁজতে ব্যাচ খরচ, উপকরণ ও উৎপাদন দেখুন। পরিধি আলাদাভাবে নিশ্চিত হয়।', 'ভাড়ার রান্নাঘরের ব্যবহার ও প্রতিটি ভাড়াটিয়ার অবদান দেখুন।'],
  th: ['ดูว่าลูกค้าคนใดกลับมาและคนใดมาน้อยลง เพื่อวางข้อเสนอที่เหมาะสม', 'คาดการณ์ยอดขายและต้นทุน เปรียบเทียบแผน แล้วนำผลไปลงมือทำ', 'รวมตารางงานพื้นฐาน คำขอลา และเอกสารของทีมเล็กไว้ในที่เดียว', 'จัดกะตามเวลาว่างและความต้องการ พร้อมจัดการสลับกะ', 'รวมข้อมูลพนักงาน เอกสาร การเริ่มงาน และคำขอ โดยมีการจัดกะรวมอยู่ด้วย', 'ตรวจเวลาเข้างาน เวลาพัก และชั่วโมงทำงานก่อนเตรียมเงินเดือน', 'รวมชั่วโมงที่อนุมัติและข้อมูลค่าจ้างเพื่อทำเงินเดือนหรือส่งให้ผู้ให้บริการ ยืนยันการรองรับประเทศก่อนตั้งค่า', 'ดูรูปแบบผลงาน การรักษาพนักงาน และทักษะ เพื่อวางแผนฝึกอบรมและจ้างงาน', 'เปรียบเทียบสาขาแฟรนไชส์และค่าธรรมเนียมเพื่อหาจุดที่ต้องการการสนับสนุน', 'ดูผลกำไรของร้านอาหาร บาร์ งานเลี้ยง และรูมเซอร์วิสของโรงแรม', 'เปรียบเทียบแบรนด์เดลิเวอรีในครัวร่วมและผลของค่าคอมมิชชันต่อกำไร', 'เปรียบเทียบราคาเสนอและต้นทุนจริงของงาน ยืนยันขอบเขตแยกต่างหาก', 'ติดตามต้นทุนต่อชุด วัตถุดิบ และผลผลิตเพื่อหาการสูญเสีย ยืนยันขอบเขตแยกต่างหาก', 'ดูการใช้พื้นที่ครัวเช่าและส่วนร่วมของผู้เช่าแต่ละราย'],
  ms: ['Lihat pelanggan yang kembali dan yang semakin jarang datang untuk merancang tawaran yang sesuai.', 'Ramalkan jualan dan kos, bandingkan rancangan dan ubah dapatan menjadi tindakan.', 'Jadual asas, permohonan cuti dan dokumen pasukan kecil di satu tempat.', 'Rancang syif mengikut ketersediaan dan permintaan serta urus pertukaran.', 'Satukan rekod pekerja, dokumen, orientasi dan permohonan. Penjadualan disertakan.', 'Semak rekod masuk, rehat dan jam bekerja sebelum menyediakan gaji.', 'Satukan jam diluluskan dan maklumat gaji untuk penggajian atau penyedia anda. Sokongan negara disahkan sebelum persediaan.', 'Lihat corak prestasi, pengekalan dan kemahiran untuk merancang latihan dan pengambilan.', 'Bandingkan lokasi francais dan royalti untuk mengenal pasti keperluan sokongan.', 'Lihat keuntungan restoran, bar, jamuan dan perkhidmatan bilik hotel.', 'Bandingkan jenama penghantaran di dapur bersama dan kesan komisen terhadap keuntungan.', 'Bandingkan sebut harga dengan kos sebenar acara. Skop disahkan berasingan.', 'Jejaki kos kelompok, bahan dan hasil pengeluaran untuk mencari pembaziran. Skop disahkan berasingan.', 'Semak penggunaan dapur sewaan dan sumbangan setiap penyewa.'],
};

export const featureHelpLabels: Record<PricingLocale, string> = {
  en: 'About {feature}', ar: 'عن {feature}', fr: 'À propos de {feature}', es: 'Acerca de {feature}', de: 'Über {feature}', nl: 'Over {feature}', pt: 'Sobre {feature}', hi: '{feature} के बारे में', ur: '{feature} کے بارے میں', it: 'Informazioni su {feature}', pl: 'O funkcji {feature}', tr: '{feature} hakkında', 'zh-Hans': '了解{feature}', ja: '{feature}について', ko: '{feature} 설명', id: 'Tentang {feature}', vi: 'Về {feature}', ro: 'Despre {feature}', sv: 'Om {feature}', bn: '{feature} সম্পর্কে', th: 'เกี่ยวกับ {feature}', ms: 'Tentang {feature}',
};

export function extraFeatureHelp(id: FeatureHelpId, locale: PricingLocale): string | undefined {
  if (locale === 'en') return englishFeatureHelp[id];
  const index = extraIds.indexOf(id as typeof extraIds[number]);
  return index < 0 ? undefined : featureHelpExtras[locale][index];
}
