import type { PricingLocale } from './locales';

// Class labels follow the backend implementation scope; fees remain reference inputs until scoped.
export const pricingPolicyCopy: Record<PricingLocale, { discount: string; setup: string; classes: readonly string[] }> = {
  en: { discount:'You receive whichever saving is greater: the saving for your number of locations or your subscription term. The maximum saving is {cap}%. Extra employee charges, additional specialist usage and setup fees do not receive this discount.', setup:'You pay one setup fee, based on the most involved setup you need. These prices are a guide. We’ll confirm connections to your systems, data transfer, payroll needs and the final fee in your proposal.', classes:['Set up yourself','Assisted setup','Standard launch','Complex setup','Payroll or large business setup'] },
  ar: { discount:'يُطبّق الأكبر من خصم الحجم أو الالتزام مرة واحدة، بسقف {cap}%. تُستثنى توسعات الموظفين والعناصر والإعداد.', setup:'رسوم إعداد واحدة وفق أعلى فئة مطبقة. هذه فئات مرجعية؛ تُؤكد التكاملات وترحيل البيانات ونطاق الرواتب في العرض.', classes:['خدمة ذاتية','A · إعداد بمساعدة','B · إطلاق قياسي','C · تعقيد مُدار','D · رواتب / مؤسسات'] },
  fr: { discount:'La remise volume ou engagement la plus élevée s’applique une fois, avec un plafond de {cap} %. Les extensions d’effectifs et d’objets et la mise en place sont exclues.', setup:'Une seule mise en place utilise la classe applicable la plus élevée. Ces classes sont indicatives ; intégrations, migration et paie sont confirmées dans la proposition.', classes:['Libre-service','A · Configuration assistée','B · Lancement standard','C · Complexité maîtrisée','D · Paie / entreprise'] },
  es: { discount:'Se aplica una vez el mayor descuento por volumen o compromiso, con un límite del {cap} %. Las ampliaciones de empleados y objetos y la implementación quedan excluidas.', setup:'Un único cargo de implementación usa la clase aplicable más alta. Son clases orientativas; las integraciones, la migración y la nómina se confirman en la propuesta.', classes:['Autoservicio','A · Configuración asistida','B · Lanzamiento estándar','C · Complejidad controlada','D · Nómina / empresa'] },
  de: { discount:'Der höhere Mengen- oder Laufzeitrabatt gilt einmal, bis maximal {cap} %. Zusätzliche Mitarbeiterplätze, Objekte und Einrichtung sind ausgeschlossen.', setup:'Eine Einrichtungsgebühr folgt der höchsten zutreffenden Klasse. Diese Klassen sind Richtwerte; Integrationen, Migration und Lohnabrechnung werden im Angebot bestätigt.', classes:['Selbstbedienung','A · Unterstützte Einrichtung','B · Standardstart','C · Gesteuerte Komplexität','D · Lohnabrechnung / Enterprise'] },
  nl: { discount:'De hoogste volume- of looptijdkorting geldt eenmaal, tot maximaal {cap}%. Extra medewerkersplaatsen, objecten en inrichting zijn uitgesloten.', setup:'Eén inrichtingsbedrag volgt de hoogste toepasselijke klasse. Dit zijn referentieklassen; integraties, migratie en loonadministratie worden in het voorstel bevestigd.', classes:['Zelfbediening','A · Begeleide inrichting','B · Standaardlancering','C · Beheerste complexiteit','D · Loonadministratie / enterprise'] },
  pt: { discount:'Aplica-se uma vez o maior desconto por volume ou compromisso, até {cap}%. Expansões de funcionários e objetos e implementação ficam excluídas.', setup:'Uma única taxa de implementação usa a maior classe aplicável. São classes de referência; integrações, migração e folha são confirmadas na proposta.', classes:['Autoatendimento','A · Configuração assistida','B · Lançamento padrão','C · Complexidade controlada','D · Folha / empresarial'] },
  it: { discount:'Si applica una volta lo sconto maggiore tra volume e durata, fino al {cap}%. Posti dipendenti aggiuntivi, oggetti e implementazione sono esclusi.', setup:'Un solo costo di implementazione segue la classe applicabile più alta. Sono classi indicative; integrazioni, migrazione e paghe sono confermate nella proposta.', classes:['Self-service','A · Configurazione assistita','B · Avvio standard','C · Complessità controllata','D · Paghe / enterprise'] },
  pl: { discount:'Wyższy rabat za liczbę lokalizacji lub okres umowy stosuje się raz, do {cap}%. Dodatkowi pracownicy, obiekty i wdrożenie są wyłączone.', setup:'Jedna opłata wdrożeniowa odpowiada najwyższej właściwej klasie. To klasy orientacyjne; integracje, migracja i płace są potwierdzane w ofercie.', classes:['Samoobsługa','A · Konfiguracja z pomocą','B · Standardowe uruchomienie','C · Kontrolowana złożoność','D · Płace / enterprise'] },
  tr: { discount:'Hacim veya taahhüt indiriminden yüksek olanı bir kez uygulanır; üst sınır %{cap}. Ek çalışan ve nesne kapasitesi ile kurulum hariçtir.', setup:'Tek kurulum ücreti en yüksek geçerli sınıfa göre belirlenir. Bunlar referans sınıflardır; entegrasyon, taşıma ve bordro kapsamı teklifte doğrulanır.', classes:['Self servis','A · Destekli yapılandırma','B · Standart başlangıç','C · Kontrollü karmaşıklık','D · Bordro / kurumsal'] },
  ro: { discount:'Reducerea mai mare pentru volum sau durată se aplică o singură dată, până la {cap}%. Extinderile de personal și obiecte și implementarea sunt excluse.', setup:'O singură taxă de implementare folosește clasa aplicabilă cea mai înaltă. Clasele sunt orientative; integrările, migrarea și salarizarea se confirmă în ofertă.', classes:['Autoservire','A · Configurare asistată','B · Lansare standard','C · Complexitate controlată','D · Salarizare / enterprise'] },
  sv: { discount:'Den högsta volym- eller bindningstidsrabatten gäller en gång, högst {cap} %. Extra medarbetarplatser, objekt och införande undantas.', setup:'En införandeavgift följer den högsta tillämpliga klassen. Klasserna är riktvärden; integrationer, migrering och lön bekräftas i förslaget.', classes:['Självservice','A · Assisterad konfiguration','B · Standardstart','C · Kontrollerad komplexitet','D · Lön / enterprise'] },
  'zh-Hans': { discount:'规模或合约折扣取较高者，仅应用一次，上限为 {cap}%。额外员工及对象容量和实施费用不参与折扣。', setup:'一次性实施费按适用的最高类别计算。以下类别仅供参考；集成、迁移及薪资范围以方案确认为准。', classes:['自助服务','A · 辅助配置','B · 标准上线','C · 复杂项目管理','D · 薪资 / 企业'] },
  ja: { discount:'拠点数または契約期間の割引の高い方を1回適用し、上限は{cap}%です。追加従業員・オブジェクト枠と導入費は対象外です。', setup:'導入費は適用される最上位クラスで一度請求されます。クラスは参考情報です。連携、移行、給与の範囲は提案で確定します。', classes:['セルフサービス','A · 設定支援','B · 標準導入','C · 複雑な導入の管理','D · 給与 / エンタープライズ'] },
  ko: { discount:'규모 또는 계약 할인 중 큰 값을 한 번 적용하며 상한은 {cap}%입니다. 추가 직원·객체 용량과 구축 비용은 제외됩니다.', setup:'구축 비용은 적용 가능한 최상위 등급으로 한 번 청구됩니다. 등급은 참고용이며 연동, 이전 및 급여 범위는 제안서에서 확정됩니다.', classes:['셀프서비스','A · 설정 지원','B · 표준 도입','C · 복잡성 관리','D · 급여 / 엔터프라이즈'] },
  id: { discount:'Diskon volume atau komitmen yang lebih besar diterapkan sekali, maksimal {cap}%. Tambahan kapasitas karyawan dan objek serta implementasi dikecualikan.', setup:'Satu biaya implementasi mengikuti kelas tertinggi yang berlaku. Kelas ini adalah referensi; integrasi, migrasi dan penggajian dikonfirmasi dalam proposal.', classes:['Mandiri','A · Konfigurasi berbantuan','B · Peluncuran standar','C · Kompleksitas terkendali','D · Penggajian / enterprise'] },
  vi: { discount:'Mức giảm theo quy mô hoặc cam kết cao hơn được áp dụng một lần, tối đa {cap}%. Phần mở rộng nhân viên, đối tượng và triển khai không được giảm.', setup:'Một phí triển khai theo nhóm áp dụng cao nhất. Đây là nhóm tham khảo; tích hợp, di chuyển dữ liệu và bảng lương được xác nhận trong đề xuất.', classes:['Tự phục vụ','A · Hỗ trợ cấu hình','B · Triển khai tiêu chuẩn','C · Kiểm soát độ phức tạp','D · Bảng lương / doanh nghiệp'] },
  ms: { discount:'Diskaun volum atau komitmen yang lebih tinggi digunakan sekali, maksimum {cap}%. Kapasiti pekerja dan objek tambahan serta pelaksanaan dikecualikan.', setup:'Satu caj pelaksanaan mengikut kelas tertinggi yang berkenaan. Kelas ini ialah rujukan; integrasi, migrasi dan gaji disahkan dalam cadangan.', classes:['Layan diri','A · Konfigurasi berbantu','B · Pelancaran standard','C · Kerumitan terkawal','D · Gaji / perusahaan'] },
  hi: { discount:'वॉल्यूम या अवधि में अधिक छूट एक बार लागू होती है, अधिकतम {cap}% तक। अतिरिक्त कर्मचारी और ऑब्जेक्ट क्षमता तथा सेटअप शामिल नहीं हैं।', setup:'एक सेटअप शुल्क लागू उच्चतम श्रेणी पर आधारित है। ये संदर्भ श्रेणियाँ हैं; एकीकरण, डेटा माइग्रेशन और पेरोल दायरा प्रस्ताव में तय होता है।', classes:['स्वयं सेवा','A · सहायता से सेटअप','B · मानक लॉन्च','C · नियंत्रित जटिलता','D · पेरोल / एंटरप्राइज़'] },
  ur: { discount:'حجم یا مدت میں زیادہ رعایت ایک بار لاگو ہوتی ہے، زیادہ سے زیادہ {cap}%۔ اضافی ملازمین اور آبجیکٹس کی گنجائش اور سیٹ اپ شامل نہیں۔', setup:'ایک سیٹ اپ فیس سب سے اعلیٰ قابل اطلاق درجے پر مبنی ہے۔ یہ حوالہ جاتی درجے ہیں؛ انضمام، منتقلی اور پے رول کا دائرہ تجویز میں طے ہوتا ہے۔', classes:['خود خدمت','A · معاون ترتیب','B · معیاری آغاز','C · منظم پیچیدگی','D · پے رول / انٹرپرائز'] },
  bn: { discount:'পরিসর বা চুক্তির মধ্যে বেশি ছাড় একবার প্রযোজ্য, সর্বোচ্চ {cap}%। অতিরিক্ত কর্মী ও অবজেক্টের ক্ষমতা এবং সেটআপ বাদ থাকে।', setup:'একটি সেটআপ ফি সর্বোচ্চ প্রযোজ্য শ্রেণির ভিত্তিতে হয়। এগুলি নির্দেশক শ্রেণি; সংযোগ, তথ্য স্থানান্তর ও বেতন প্রক্রিয়ার পরিসর প্রস্তাবে নিশ্চিত হয়।', classes:['স্বয়ং সেবা','A · সহায়তাসহ কনফিগারেশন','B · মানক চালু','C · নিয়ন্ত্রিত জটিলতা','D · বেতন / এন্টারপ্রাইজ'] },
  th: { discount:'ใช้ส่วนลดตามจำนวนสาขาหรือระยะสัญญาที่สูงกว่าครั้งเดียว สูงสุด {cap}% ไม่รวมการขยายจำนวนพนักงาน วัตถุ และค่าติดตั้ง', setup:'ค่าติดตั้งครั้งเดียวใช้ระดับที่เกี่ยวข้องสูงสุด ระดับนี้เป็นข้อมูลอ้างอิง การเชื่อมต่อ การย้ายข้อมูล และขอบเขตเงินเดือนจะยืนยันในข้อเสนอ', classes:['บริการตนเอง','A · ช่วยตั้งค่า','B · เริ่มใช้งานมาตรฐาน','C · จัดการความซับซ้อน','D · เงินเดือน / องค์กร'] },
};
