/**
 * The quote screen, in all 22 locales.
 *
 * The summary is the screen a buyer forwards, and it carried its most important
 * lines as literal English in JSX — the monthly investment, the two rails, the
 * combined total, the one-time implementation, the per-object overlay
 * disclosure and the commitment term. A visitor on the German site configured a
 * quote in German and then read the number that decides the deal in English.
 *
 * Every locale is written here rather than inherited from the generated packs,
 * because those packs are produced outside this repo and drift; the quote
 * screen is the last place that should degrade to English.
 *
 * Protected terms stay literal in every locale: Sundae, Core, Crew, Watchtower,
 * Foresight, and the package names.
 */

export interface QuoteSummaryCopy {
  yourConfiguration: string;
  monthlyInvestment: string;
  coreRail: string;
  crewRail: string;
  combinedMonthly: string;
  implementationOneTime: string;
  indicativeOnly: string;
  billedPerObject: string;
  objectChargeNote: string;
  commitmentTerm: string;
  termMonthly: string;
  termAnnual: string;
  termTwoYear: string;
  /** "save {percent}" — percent arrives pre-formatted, e.g. "10%". */
  saveShort: string;
  /** "Volume ({locations} locations)" */
  volumeLabel: string;
  earlyAdopter: string;
  /** "{percent} not applied — the commitment term is larger" */
  volumeNotApplied: string;
  /** "{percent} not applied — volume is larger" */
  termNotApplied: string;
  crewStackReady: string;
  crewCurveNote: string;
  crewSubstrateNote: string;
  /** ROI framing — the model is a planning aid, never a measured outcome. */
  modelledHeading: string;
  modelledNote: string;
  basisLabel: string;
}

export const quoteSummaryCopy: Record<string, QuoteSummaryCopy> = {
  en: {
    yourConfiguration: 'Your configuration',
    monthlyInvestment: 'Monthly investment',
    coreRail: 'Core rail',
    crewRail: 'Crew rail (operational substrate)',
    combinedMonthly: 'Combined monthly',
    implementationOneTime: 'Implementation (one-time)',
    indicativeOnly: 'Indicative only — confirm your systems and we will scope the exact class.',
    billedPerObject: 'Billed per active object',
    objectChargeNote: 'Charged only while the object is active, and never discounted.',
    commitmentTerm: 'Commitment term',
    termMonthly: 'Monthly',
    termAnnual: 'Annual',
    termTwoYear: '2 years',
    saveShort: 'save {percent}',
    volumeLabel: 'Volume ({locations} locations)',
    earlyAdopter: 'Early adopter',
    volumeNotApplied: 'Volume {percent} not applied — the commitment term is larger',
    termNotApplied: 'Commitment term {percent} not applied — volume is larger',
    crewStackReady: 'Your Crew stack is ready',
    crewCurveNote: 'Crew prices on a declining curve — the first location at the anchor, then each added location cheaper by band',
    crewSubstrateNote:
      'Multi-region payroll readiness, scheduling, and HR ops on one operational substrate.',
    modelledHeading: 'Modelled estimate — not a measured outcome',
    modelledNote:
      'Every figure here is a planning model built from published assumption ranges, shown per line below. Sundae has not yet published verified customer results, so treat this as a way to frame the conversation with your own numbers — not as a forecast.',
    basisLabel: 'Basis',
  },
  ar: {
    yourConfiguration: 'إعدادك',
    monthlyInvestment: 'الاستثمار الشهري',
    coreRail: 'مسار Core',
    crewRail: 'مسار Crew (الأساس التشغيلي)',
    combinedMonthly: 'الإجمالي الشهري المشترك',
    implementationOneTime: 'التنفيذ (لمرة واحدة)',
    indicativeOnly: 'إرشادي فقط — أكّد أنظمتك وسنحدد الفئة بدقة.',
    billedPerObject: 'يُحتسب لكل عنصر نشط',
    objectChargeNote: 'يُحتسب فقط أثناء نشاط العنصر، ولا يخضع لأي خصم.',
    commitmentTerm: 'مدة الالتزام',
    termMonthly: 'شهري',
    termAnnual: 'سنوي',
    termTwoYear: 'سنتان',
    saveShort: 'وفّر {percent}',
    volumeLabel: 'الحجم ({locations} موقعاً)',
    earlyAdopter: 'المشترك المبكر',
    volumeNotApplied: 'خصم الحجم {percent} غير مطبّق — مدة الالتزام أكبر',
    termNotApplied: 'خصم مدة الالتزام {percent} غير مطبّق — الحجم أكبر',
    crewStackReady: 'حزمة Crew جاهزة',
    crewCurveNote: 'يُسعَّر Crew على منحنى تنازلي — الموقع الأول بالسعر الأساسي، ثم يقل سعر كل موقع إضافي حسب الشريحة',
    crewSubstrateNote:
      'جاهزية الرواتب متعددة المناطق والجدولة وعمليات الموارد البشرية على أساس تشغيلي واحد.',
    modelledHeading: 'تقدير نموذجي — وليس نتيجة مقيسة',
    modelledNote:
      'كل رقم هنا نموذج تخطيطي مبني على نطاقات افتراضية منشورة، معروضة لكل بند أدناه. لم تنشر Sundae بعد نتائج عملاء موثقة، لذا استخدمه لتأطير النقاش بأرقامك أنت — لا كتوقّع.',
    basisLabel: 'الأساس',
  },
  fr: {
    yourConfiguration: 'Votre configuration',
    monthlyInvestment: 'Investissement mensuel',
    coreRail: 'Volet Core',
    crewRail: 'Volet Crew (socle opérationnel)',
    combinedMonthly: 'Total mensuel combiné',
    implementationOneTime: 'Mise en œuvre (unique)',
    indicativeOnly: 'Indicatif — confirmez vos systèmes et nous cadrerons la classe exacte.',
    billedPerObject: 'Facturé par objet actif',
    objectChargeNote: "Facturé uniquement tant que l'objet est actif, et jamais remisé.",
    commitmentTerm: 'Durée d’engagement',
    termMonthly: 'Mensuel',
    termAnnual: 'Annuel',
    termTwoYear: '2 ans',
    saveShort: 'économisez {percent}',
    volumeLabel: 'Volume ({locations} sites)',
    earlyAdopter: 'Client early adopter',
    volumeNotApplied: 'Remise volume {percent} non appliquée — l’engagement est plus avantageux',
    termNotApplied: 'Remise d’engagement {percent} non appliquée — le volume est plus avantageux',
    crewStackReady: 'Votre configuration Crew est prête',
    crewCurveNote: 'Crew suit un barème dégressif — le premier site au tarif d’ancrage, puis chaque site ajouté moins cher par tranche',
    crewSubstrateNote:
      'Préparation de la paie multi-pays, planification et RH sur un seul socle opérationnel.',
    modelledHeading: 'Estimation modélisée — pas un résultat mesuré',
    modelledNote:
      "Chaque chiffre est un modèle de planification construit à partir de fourchettes d'hypothèses publiées, détaillées ligne par ligne ci-dessous. Sundae n'a pas encore publié de résultats clients vérifiés : utilisez-le pour cadrer la discussion avec vos propres chiffres, pas comme une prévision.",
    basisLabel: 'Base',
  },
  es: {
    yourConfiguration: 'Tu configuración',
    monthlyInvestment: 'Inversión mensual',
    coreRail: 'Vía Core',
    crewRail: 'Vía Crew (base operativa)',
    combinedMonthly: 'Total mensual combinado',
    implementationOneTime: 'Implementación (pago único)',
    indicativeOnly: 'Solo orientativo: confirma tus sistemas y definiremos la clase exacta.',
    billedPerObject: 'Se factura por objeto activo',
    objectChargeNote: 'Se cobra solo mientras el objeto está activo, y nunca con descuento.',
    commitmentTerm: 'Plazo de compromiso',
    termMonthly: 'Mensual',
    termAnnual: 'Anual',
    termTwoYear: '2 años',
    saveShort: 'ahorra {percent}',
    volumeLabel: 'Volumen ({locations} locales)',
    earlyAdopter: 'Cliente pionero',
    volumeNotApplied: 'Descuento por volumen {percent} no aplicado: el plazo es mayor',
    termNotApplied: 'Descuento por plazo {percent} no aplicado: el volumen es mayor',
    crewStackReady: 'Tu configuración de Crew está lista',
    crewCurveNote: 'Crew se tarifica en escala decreciente: el primer local al precio ancla y cada local añadido más barato por tramo',
    crewSubstrateNote:
      'Preparación de nóminas multipaís, turnos y operaciones de RR. HH. sobre una única base operativa.',
    modelledHeading: 'Estimación modelada, no un resultado medido',
    modelledNote:
      'Cada cifra es un modelo de planificación construido con rangos de supuestos publicados, detallados línea por línea abajo. Sundae aún no ha publicado resultados verificados de clientes, así que úsalo para encuadrar la conversación con tus propios números, no como un pronóstico.',
    basisLabel: 'Base',
  },
  de: {
    yourConfiguration: 'Ihre Konfiguration',
    monthlyInvestment: 'Monatliche Investition',
    coreRail: 'Core-Strang',
    crewRail: 'Crew-Strang (operative Basis)',
    combinedMonthly: 'Kombiniert monatlich',
    implementationOneTime: 'Einführung (einmalig)',
    indicativeOnly: 'Nur Richtwert — bestätigen Sie Ihre Systeme, dann bestimmen wir die genaue Klasse.',
    billedPerObject: 'Abrechnung je aktivem Objekt',
    objectChargeNote: 'Wird nur berechnet, solange das Objekt aktiv ist, und nie rabattiert.',
    commitmentTerm: 'Vertragslaufzeit',
    termMonthly: 'Monatlich',
    termAnnual: 'Jährlich',
    termTwoYear: '2 Jahre',
    saveShort: '{percent} sparen',
    volumeLabel: 'Volumen ({locations} Standorte)',
    earlyAdopter: 'Early Adopter',
    volumeNotApplied: 'Mengenrabatt {percent} nicht angewendet — die Laufzeit ist höher',
    termNotApplied: 'Laufzeitrabatt {percent} nicht angewendet — das Volumen ist höher',
    crewStackReady: 'Ihr Crew-Stack steht',
    crewCurveNote: 'Crew rechnet auf einer degressiven Staffel ab — der erste Standort zum Ankerpreis, jeder weitere je Stufe günstiger',
    crewSubstrateNote:
      'Lohnbereitschaft für mehrere Regionen, Dienstplanung und HR-Betrieb auf einer operativen Basis.',
    modelledHeading: 'Modellrechnung — kein gemessenes Ergebnis',
    modelledNote:
      'Jede Zahl hier ist eine Planungsrechnung auf Basis veröffentlichter Annahmebandbreiten, unten je Position ausgewiesen. Sundae hat noch keine verifizierten Kundenergebnisse veröffentlicht: Nutzen Sie sie, um das Gespräch mit Ihren eigenen Zahlen zu rahmen, nicht als Prognose.',
    basisLabel: 'Grundlage',
  },
  nl: {
    yourConfiguration: 'Uw configuratie',
    monthlyInvestment: 'Maandelijkse investering',
    coreRail: 'Core-spoor',
    crewRail: 'Crew-spoor (operationele basis)',
    combinedMonthly: 'Gecombineerd per maand',
    implementationOneTime: 'Implementatie (eenmalig)',
    indicativeOnly: 'Alleen indicatief — bevestig uw systemen en wij bepalen de exacte klasse.',
    billedPerObject: 'Afgerekend per actief object',
    objectChargeNote: 'Wordt alleen berekend zolang het object actief is, en nooit met korting.',
    commitmentTerm: 'Contractduur',
    termMonthly: 'Maandelijks',
    termAnnual: 'Jaarlijks',
    termTwoYear: '2 jaar',
    saveShort: 'bespaar {percent}',
    volumeLabel: 'Volume ({locations} locaties)',
    earlyAdopter: 'Early adopter',
    volumeNotApplied: 'Volumekorting {percent} niet toegepast — de looptijd is gunstiger',
    termNotApplied: 'Looptijdkorting {percent} niet toegepast — het volume is gunstiger',
    crewStackReady: 'Uw Crew-stack staat klaar',
    crewCurveNote: 'Crew rekent af op een degressieve staffel — de eerste locatie tegen het ankertarief, elke volgende goedkoper per schijf',
    crewSubstrateNote:
      'Loonklaar in meerdere regio\'s, roosters en HR-operatie op één operationele basis.',
    modelledHeading: 'Modelmatige schatting — geen gemeten uitkomst',
    modelledNote:
      'Elk bedrag hier is een planningsmodel op basis van gepubliceerde aannamebandbreedtes, hieronder per regel getoond. Sundae heeft nog geen geverifieerde klantresultaten gepubliceerd: gebruik dit om het gesprek met uw eigen cijfers te kaderen, niet als prognose.',
    basisLabel: 'Grondslag',
  },
  pt: {
    yourConfiguration: 'A sua configuração',
    monthlyInvestment: 'Investimento mensal',
    coreRail: 'Via Core',
    crewRail: 'Via Crew (base operacional)',
    combinedMonthly: 'Total mensal combinado',
    implementationOneTime: 'Implementação (pagamento único)',
    indicativeOnly: 'Apenas indicativo — confirme os seus sistemas e definiremos a classe exata.',
    billedPerObject: 'Cobrado por objeto ativo',
    objectChargeNote: 'Cobrado apenas enquanto o objeto estiver ativo, e nunca com desconto.',
    commitmentTerm: 'Prazo de compromisso',
    termMonthly: 'Mensal',
    termAnnual: 'Anual',
    termTwoYear: '2 anos',
    saveShort: 'poupe {percent}',
    volumeLabel: 'Volume ({locations} locais)',
    earlyAdopter: 'Cliente pioneiro',
    volumeNotApplied: 'Desconto por volume {percent} não aplicado — o prazo é maior',
    termNotApplied: 'Desconto por prazo {percent} não aplicado — o volume é maior',
    crewStackReady: 'A sua configuração Crew está pronta',
    crewCurveNote: 'O Crew é cobrado numa escala decrescente — o primeiro local ao preço âncora e cada local adicional mais barato por escalão',
    crewSubstrateNote:
      'Prontidão de folha em várias regiões, escalas e operações de RH numa única base operacional.',
    modelledHeading: 'Estimativa modelada — não um resultado medido',
    modelledNote:
      'Cada valor aqui é um modelo de planeamento construído a partir de intervalos de pressupostos publicados, apresentados linha a linha abaixo. A Sundae ainda não publicou resultados verificados de clientes: use isto para enquadrar a conversa com os seus próprios números, não como previsão.',
    basisLabel: 'Base',
  },
  hi: {
    yourConfiguration: 'आपका कॉन्फ़िगरेशन',
    monthlyInvestment: 'मासिक निवेश',
    coreRail: 'Core पथ',
    crewRail: 'Crew पथ (परिचालन आधार)',
    combinedMonthly: 'संयुक्त मासिक',
    implementationOneTime: 'कार्यान्वयन (एकबारगी)',
    indicativeOnly: 'केवल संकेतात्मक — अपने सिस्टम की पुष्टि करें, हम सटीक श्रेणी तय करेंगे।',
    billedPerObject: 'प्रति सक्रिय ऑब्जेक्ट बिल',
    objectChargeNote: 'शुल्क तभी लगता है जब ऑब्जेक्ट सक्रिय हो, और उस पर छूट नहीं मिलती।',
    commitmentTerm: 'प्रतिबद्धता अवधि',
    termMonthly: 'मासिक',
    termAnnual: 'वार्षिक',
    termTwoYear: '2 वर्ष',
    saveShort: '{percent} बचाएँ',
    volumeLabel: 'वॉल्यूम ({locations} लोकेशन)',
    earlyAdopter: 'अर्ली अडॉप्टर',
    volumeNotApplied: 'वॉल्यूम छूट {percent} लागू नहीं — अवधि छूट अधिक है',
    termNotApplied: 'अवधि छूट {percent} लागू नहीं — वॉल्यूम छूट अधिक है',
    crewStackReady: 'आपका Crew स्टैक तैयार है',
    crewCurveNote: 'Crew की कीमत घटती दर पर लगती है — पहला लोकेशन एंकर मूल्य पर, फिर हर अतिरिक्त लोकेशन बैंड के अनुसार सस्ता',
    crewSubstrateNote:
      'एक ही परिचालन आधार पर बहु-क्षेत्रीय पेरोल तैयारी, शेड्यूलिंग और HR संचालन।',
    modelledHeading: 'मॉडल आधारित अनुमान — मापा गया परिणाम नहीं',
    modelledNote:
      'यहाँ हर आंकड़ा प्रकाशित अनुमान-सीमाओं पर बना एक योजना मॉडल है, नीचे प्रति पंक्ति दिखाया गया। Sundae ने अभी सत्यापित ग्राहक परिणाम प्रकाशित नहीं किए हैं — इसे अपने आंकड़ों के साथ बातचीत की रूपरेखा मानें, पूर्वानुमान नहीं।',
    basisLabel: 'आधार',
  },
  ur: {
    yourConfiguration: 'آپ کی کنفیگریشن',
    monthlyInvestment: 'ماہانہ سرمایہ کاری',
    coreRail: 'Core راستہ',
    crewRail: 'Crew راستہ (آپریشنل بنیاد)',
    combinedMonthly: 'مشترکہ ماہانہ',
    implementationOneTime: 'نفاذ (ایک بار)',
    indicativeOnly: 'صرف اندازہ — اپنے سسٹمز کی تصدیق کریں، ہم درست کلاس طے کریں گے۔',
    billedPerObject: 'ہر فعال آبجیکٹ پر بل',
    objectChargeNote: 'چارج صرف اُس وقت لگتا ہے جب آبجیکٹ فعال ہو، اور اس پر رعایت نہیں ملتی۔',
    commitmentTerm: 'معاہدے کی مدت',
    termMonthly: 'ماہانہ',
    termAnnual: 'سالانہ',
    termTwoYear: '2 سال',
    saveShort: '{percent} بچائیں',
    volumeLabel: 'حجم ({locations} مقامات)',
    earlyAdopter: 'ابتدائی صارف',
    volumeNotApplied: 'حجم رعایت {percent} لاگو نہیں — مدت کی رعایت زیادہ ہے',
    termNotApplied: 'مدت کی رعایت {percent} لاگو نہیں — حجم کی رعایت زیادہ ہے',
    crewStackReady: 'آپ کا Crew اسٹیک تیار ہے',
    crewCurveNote: 'Crew کی قیمت گھٹتی شرح پر لگتی ہے — پہلا مقام بنیادی قیمت پر، پھر ہر اضافی مقام بینڈ کے مطابق سستا',
    crewSubstrateNote:
      'ایک ہی آپریشنل بنیاد پر کثیر خطہ پے رول تیاری، شیڈولنگ اور HR آپریشنز۔',
    modelledHeading: 'ماڈل پر مبنی تخمینہ — ماپا گیا نتیجہ نہیں',
    modelledNote:
      'یہاں ہر عدد شائع شدہ مفروضہ حدود پر بنایا گیا منصوبہ بندی ماڈل ہے، نیچے فی سطر دکھایا گیا۔ Sundae نے ابھی تصدیق شدہ کسٹمر نتائج شائع نہیں کیے — اسے اپنے اعداد کے ساتھ گفتگو کی بنیاد سمجھیں، پیش گوئی نہیں۔',
    basisLabel: 'بنیاد',
  },
  it: {
    yourConfiguration: 'La tua configurazione',
    monthlyInvestment: 'Investimento mensile',
    coreRail: 'Binario Core',
    crewRail: 'Binario Crew (base operativa)',
    combinedMonthly: 'Totale mensile combinato',
    implementationOneTime: 'Implementazione (una tantum)',
    indicativeOnly: 'Solo indicativo — conferma i tuoi sistemi e definiremo la classe esatta.',
    billedPerObject: 'Fatturato per oggetto attivo',
    objectChargeNote: 'Addebitato solo finché l’oggetto è attivo, e mai scontato.',
    commitmentTerm: 'Durata dell’impegno',
    termMonthly: 'Mensile',
    termAnnual: 'Annuale',
    termTwoYear: '2 anni',
    saveShort: 'risparmia {percent}',
    volumeLabel: 'Volume ({locations} sedi)',
    earlyAdopter: 'Cliente early adopter',
    volumeNotApplied: 'Sconto volume {percent} non applicato — la durata è maggiore',
    termNotApplied: 'Sconto durata {percent} non applicato — il volume è maggiore',
    crewStackReady: 'Il tuo stack Crew è pronto',
    crewCurveNote: 'Crew si tariffa su una curva decrescente: la prima sede al prezzo di ancoraggio, poi ogni sede aggiunta più economica per fascia',
    crewSubstrateNote:
      'Buste paga pronte in più aree, turni e operazioni HR su un’unica base operativa.',
    modelledHeading: 'Stima modellata — non un risultato misurato',
    modelledNote:
      'Ogni cifra è un modello di pianificazione costruito su intervalli di ipotesi pubblicati, mostrati voce per voce qui sotto. Sundae non ha ancora pubblicato risultati verificati dei clienti: usalo per impostare la conversazione con i tuoi numeri, non come previsione.',
    basisLabel: 'Base',
  },
  pl: {
    yourConfiguration: 'Twoja konfiguracja',
    monthlyInvestment: 'Inwestycja miesięczna',
    coreRail: 'Tor Core',
    crewRail: 'Tor Crew (podstawa operacyjna)',
    combinedMonthly: 'Łącznie miesięcznie',
    implementationOneTime: 'Wdrożenie (jednorazowo)',
    indicativeOnly: 'Tylko orientacyjnie — potwierdź swoje systemy, a określimy dokładną klasę.',
    billedPerObject: 'Rozliczane za aktywny obiekt',
    objectChargeNote: 'Naliczane tylko wtedy, gdy obiekt jest aktywny, i nigdy z rabatem.',
    commitmentTerm: 'Okres zobowiązania',
    termMonthly: 'Miesięcznie',
    termAnnual: 'Rocznie',
    termTwoYear: '2 lata',
    saveShort: 'oszczędź {percent}',
    volumeLabel: 'Wolumen ({locations} lokalizacji)',
    earlyAdopter: 'Klient wczesny',
    volumeNotApplied: 'Rabat wolumenowy {percent} nieprzyznany — rabat za okres jest wyższy',
    termNotApplied: 'Rabat za okres {percent} nieprzyznany — rabat wolumenowy jest wyższy',
    crewStackReady: 'Twój stack Crew jest gotowy',
    crewCurveNote: 'Crew rozlicza się według skali degresywnej — pierwsza lokalizacja w cenie bazowej, każda kolejna tańsza według progu',
    crewSubstrateNote:
      'Gotowość płacowa w wielu regionach, grafiki i operacje HR na jednej podstawie operacyjnej.',
    modelledHeading: 'Szacunek modelowy — nie zmierzony wynik',
    modelledNote:
      'Każda kwota to model planistyczny oparty na opublikowanych zakresach założeń, pokazanych poniżej dla każdej pozycji. Sundae nie opublikowało jeszcze zweryfikowanych wyników klientów: potraktuj to jako ramę do rozmowy o własnych liczbach, nie jako prognozę.',
    basisLabel: 'Podstawa',
  },
  tr: {
    yourConfiguration: 'Yapılandırmanız',
    monthlyInvestment: 'Aylık yatırım',
    coreRail: 'Core hattı',
    crewRail: 'Crew hattı (operasyonel temel)',
    combinedMonthly: 'Birleşik aylık',
    implementationOneTime: 'Devreye alma (tek seferlik)',
    indicativeOnly: 'Yalnızca gösterge — sistemlerinizi doğrulayın, kesin sınıfı birlikte belirleyelim.',
    billedPerObject: 'Aktif nesne başına faturalanır',
    objectChargeNote: 'Yalnızca nesne aktifken ücretlendirilir ve hiçbir zaman indirime girmez.',
    commitmentTerm: 'Taahhüt süresi',
    termMonthly: 'Aylık',
    termAnnual: 'Yıllık',
    termTwoYear: '2 yıl',
    saveShort: '{percent} tasarruf',
    volumeLabel: 'Hacim ({locations} lokasyon)',
    earlyAdopter: 'Erken müşteri',
    volumeNotApplied: 'Hacim indirimi {percent} uygulanmadı — taahhüt indirimi daha yüksek',
    termNotApplied: 'Taahhüt indirimi {percent} uygulanmadı — hacim indirimi daha yüksek',
    crewStackReady: 'Crew yapılandırmanız hazır',
    crewCurveNote: 'Crew azalan bir eğriyle fiyatlanır — ilk lokasyon çıpa fiyatından, sonra eklenen her lokasyon kademeye göre daha ucuz',
    crewSubstrateNote:
      'Tek bir operasyonel temelde çok bölgeli bordro hazırlığı, vardiya ve İK operasyonu.',
    modelledHeading: 'Modellenmiş tahmin — ölçülmüş bir sonuç değil',
    modelledNote:
      'Buradaki her rakam, yayımlanmış varsayım aralıklarından kurulmuş bir planlama modelidir ve aşağıda satır satır gösterilir. Sundae henüz doğrulanmış müşteri sonuçları yayımlamadı: bunu kendi rakamlarınızla konuşmayı çerçevelemek için kullanın, bir öngörü olarak değil.',
    basisLabel: 'Dayanak',
  },
  'zh-Hans': {
    yourConfiguration: '您的配置',
    monthlyInvestment: '每月投入',
    coreRail: 'Core 线',
    crewRail: 'Crew 线（运营底座）',
    combinedMonthly: '合计每月',
    implementationOneTime: '实施（一次性）',
    indicativeOnly: '仅供参考——确认您的系统后，我们会界定确切等级。',
    billedPerObject: '按活跃对象计费',
    objectChargeNote: '仅在对象活跃期间收费，且不参与任何折扣。',
    commitmentTerm: '承诺期限',
    termMonthly: '按月',
    termAnnual: '按年',
    termTwoYear: '两年',
    saveShort: '省 {percent}',
    volumeLabel: '规模（{locations} 家门店）',
    earlyAdopter: '早期客户',
    volumeNotApplied: '规模折扣 {percent} 未适用——承诺期折扣更高',
    termNotApplied: '承诺期折扣 {percent} 未适用——规模折扣更高',
    crewStackReady: '您的 Crew 配置已就绪',
    crewCurveNote: 'Crew 按递减曲线计价——首个门店按锚定价，其后每增加一个门店按band更低',
    crewSubstrateNote: '在同一运营底座上完成多地区薪酬就绪、排班与人力资源运营。',
    modelledHeading: '模型测算——并非实测结果',
    modelledNote:
      '此处每个数字都是基于公开假设区间构建的规划模型，下方按项列出。Sundae 尚未公布经核实的客户成果，请将其作为结合您自身数据展开讨论的起点，而非预测。',
    basisLabel: '依据',
  },
  ja: {
    yourConfiguration: 'ご利用構成',
    monthlyInvestment: '月額のご負担',
    coreRail: 'Core ライン',
    crewRail: 'Crew ライン（オペレーション基盤）',
    combinedMonthly: '合計月額',
    implementationOneTime: '導入費用（初回のみ）',
    indicativeOnly: '目安です。ご利用システムを確認のうえ、正確なクラスを確定します。',
    billedPerObject: 'アクティブなオブジェクト単位で課金',
    objectChargeNote: 'オブジェクトが有効な期間のみ課金され、割引の対象にはなりません。',
    commitmentTerm: '契約期間',
    termMonthly: '月々',
    termAnnual: '年間',
    termTwoYear: '2年',
    saveShort: '{percent} お得',
    volumeLabel: '規模（{locations} 店舗）',
    earlyAdopter: 'アーリーアダプター',
    volumeNotApplied: '規模割引 {percent} は非適用——契約期間割引の方が大きいため',
    termNotApplied: '契約期間割引 {percent} は非適用——規模割引の方が大きいため',
    crewStackReady: 'Crew の構成が整いました',
    crewCurveNote: 'Crew は逓減カーブで課金されます。最初の店舗はアンカー価格、以降は帯ごとに単価が下がります',
    crewSubstrateNote: '多地域の給与対応、シフト管理、HR業務を単一のオペレーション基盤で。',
    modelledHeading: 'モデル試算です。実測値ではありません',
    modelledNote:
      'ここに表示される数値は、公開された前提レンジから組み立てた計画モデルで、下に項目ごとの根拠を示しています。Sundae は検証済みの顧客成果をまだ公表していません。予測としてではなく、御社の数値で議論を組み立てるための出発点としてご利用ください。',
    basisLabel: '根拠',
  },
  ko: {
    yourConfiguration: '고객님의 구성',
    monthlyInvestment: '월 투자액',
    coreRail: 'Core 라인',
    crewRail: 'Crew 라인(운영 기반)',
    combinedMonthly: '합산 월 금액',
    implementationOneTime: '구축 비용(1회성)',
    indicativeOnly: '참고용입니다. 사용 중인 시스템을 확인한 뒤 정확한 등급을 확정합니다.',
    billedPerObject: '활성 오브젝트 단위 과금',
    objectChargeNote: '오브젝트가 활성일 때만 과금되며, 할인 대상이 아닙니다.',
    commitmentTerm: '약정 기간',
    termMonthly: '월간',
    termAnnual: '연간',
    termTwoYear: '2년',
    saveShort: '{percent} 절감',
    volumeLabel: '규모({locations}개 지점)',
    earlyAdopter: '얼리 어답터',
    volumeNotApplied: '수량 할인 {percent} 미적용 — 약정 할인이 더 큽니다',
    termNotApplied: '약정 할인 {percent} 미적용 — 수량 할인이 더 큽니다',
    crewStackReady: 'Crew 구성이 준비되었습니다',
    crewCurveNote: 'Crew는 체감 곡선으로 과금됩니다 — 첫 지점은 기준가, 이후 추가 지점은 구간별로 더 저렴해집니다',
    crewSubstrateNote: '하나의 운영 기반에서 다지역 급여 준비, 근무 일정, HR 운영을 처리합니다.',
    modelledHeading: '모델 추정치 — 측정된 결과가 아닙니다',
    modelledNote:
      '여기의 모든 수치는 공개된 가정 범위로 구성한 계획 모델이며, 아래에 항목별 근거를 표시했습니다. Sundae는 아직 검증된 고객 성과를 공개하지 않았습니다. 예측이 아니라 고객사의 숫자로 논의를 시작하는 출발점으로 사용해 주세요.',
    basisLabel: '근거',
  },
  id: {
    yourConfiguration: 'Konfigurasi Anda',
    monthlyInvestment: 'Investasi bulanan',
    coreRail: 'Jalur Core',
    crewRail: 'Jalur Crew (fondasi operasional)',
    combinedMonthly: 'Total bulanan gabungan',
    implementationOneTime: 'Implementasi (sekali bayar)',
    indicativeOnly: 'Hanya indikatif — konfirmasikan sistem Anda dan kami tentukan kelas pastinya.',
    billedPerObject: 'Ditagih per objek aktif',
    objectChargeNote: 'Hanya ditagih selama objek aktif, dan tidak pernah didiskon.',
    commitmentTerm: 'Masa komitmen',
    termMonthly: 'Bulanan',
    termAnnual: 'Tahunan',
    termTwoYear: '2 tahun',
    saveShort: 'hemat {percent}',
    volumeLabel: 'Volume ({locations} lokasi)',
    earlyAdopter: 'Pelanggan awal',
    volumeNotApplied: 'Diskon volume {percent} tidak berlaku — diskon masa komitmen lebih besar',
    termNotApplied: 'Diskon masa komitmen {percent} tidak berlaku — diskon volume lebih besar',
    crewStackReady: 'Konfigurasi Crew Anda siap',
    crewCurveNote: 'Crew dihitung dengan kurva menurun — lokasi pertama pada harga jangkar, lalu tiap lokasi tambahan lebih murah per band',
    crewSubstrateNote:
      'Kesiapan penggajian multi-wilayah, penjadwalan, dan operasi HR dalam satu fondasi operasional.',
    modelledHeading: 'Estimasi model — bukan hasil terukur',
    modelledNote:
      'Setiap angka di sini adalah model perencanaan yang dibangun dari rentang asumsi yang dipublikasikan, ditampilkan per baris di bawah. Sundae belum memublikasikan hasil pelanggan terverifikasi, jadi gunakan ini untuk membingkai percakapan dengan angka Anda sendiri, bukan sebagai ramalan.',
    basisLabel: 'Dasar',
  },
  vi: {
    yourConfiguration: 'Cấu hình của bạn',
    monthlyInvestment: 'Chi phí hằng tháng',
    coreRail: 'Nhánh Core',
    crewRail: 'Nhánh Crew (nền tảng vận hành)',
    combinedMonthly: 'Tổng hằng tháng',
    implementationOneTime: 'Triển khai (một lần)',
    indicativeOnly: 'Chỉ mang tính tham khảo — xác nhận hệ thống của bạn để chúng tôi xác định đúng hạng.',
    billedPerObject: 'Tính phí theo đối tượng đang hoạt động',
    objectChargeNote: 'Chỉ tính phí khi đối tượng còn hoạt động, và không bao giờ được chiết khấu.',
    commitmentTerm: 'Thời hạn cam kết',
    termMonthly: 'Hằng tháng',
    termAnnual: 'Hằng năm',
    termTwoYear: '2 năm',
    saveShort: 'tiết kiệm {percent}',
    volumeLabel: 'Quy mô ({locations} địa điểm)',
    earlyAdopter: 'Khách hàng tiên phong',
    volumeNotApplied: 'Chiết khấu quy mô {percent} không áp dụng — chiết khấu cam kết lớn hơn',
    termNotApplied: 'Chiết khấu cam kết {percent} không áp dụng — chiết khấu quy mô lớn hơn',
    crewStackReady: 'Cấu hình Crew của bạn đã sẵn sàng',
    crewCurveNote: 'Crew tính theo đường cong giảm dần — địa điểm đầu tiên theo giá neo, sau đó mỗi địa điểm thêm rẻ hơn theo bậc',
    crewSubstrateNote:
      'Sẵn sàng tính lương đa khu vực, xếp lịch và vận hành nhân sự trên một nền tảng duy nhất.',
    modelledHeading: 'Ước tính theo mô hình — không phải kết quả đo được',
    modelledNote:
      'Mọi con số ở đây là mô hình lập kế hoạch dựng từ các khoảng giả định đã công bố, hiển thị theo từng dòng bên dưới. Sundae chưa công bố kết quả khách hàng đã kiểm chứng, vì vậy hãy dùng nó để định khung trao đổi bằng số liệu của bạn, không phải như một dự báo.',
    basisLabel: 'Cơ sở',
  },
  ro: {
    yourConfiguration: 'Configurația ta',
    monthlyInvestment: 'Investiție lunară',
    coreRail: 'Ramura Core',
    crewRail: 'Ramura Crew (baza operațională)',
    combinedMonthly: 'Total lunar combinat',
    implementationOneTime: 'Implementare (o singură dată)',
    indicativeOnly: 'Doar orientativ — confirmă-ți sistemele și stabilim clasa exactă.',
    billedPerObject: 'Facturat per obiect activ',
    objectChargeNote: 'Se taxează doar cât timp obiectul este activ și nu se reduce niciodată.',
    commitmentTerm: 'Durata angajamentului',
    termMonthly: 'Lunar',
    termAnnual: 'Anual',
    termTwoYear: '2 ani',
    saveShort: 'economisești {percent}',
    volumeLabel: 'Volum ({locations} locații)',
    earlyAdopter: 'Client timpuriu',
    volumeNotApplied: 'Reducerea de volum {percent} nu se aplică — cea de angajament este mai mare',
    termNotApplied: 'Reducerea de angajament {percent} nu se aplică — cea de volum este mai mare',
    crewStackReady: 'Configurația ta Crew este gata',
    crewCurveNote: 'Crew se tarifează pe o curbă descrescătoare — prima locație la prețul de ancoră, apoi fiecare locație adăugată mai ieftină pe tranșă',
    crewSubstrateNote:
      'Pregătire salarizare multi-regiune, programare și operațiuni HR pe o singură bază operațională.',
    modelledHeading: 'Estimare modelată — nu un rezultat măsurat',
    modelledNote:
      'Fiecare cifră de aici este un model de planificare construit din intervale de ipoteze publicate, afișate pe fiecare rând mai jos. Sundae nu a publicat încă rezultate verificate ale clienților: folosește-l pentru a încadra discuția cu propriile cifre, nu ca pe o prognoză.',
    basisLabel: 'Bază',
  },
  sv: {
    yourConfiguration: 'Din konfiguration',
    monthlyInvestment: 'Månadskostnad',
    coreRail: 'Core-spår',
    crewRail: 'Crew-spår (operativ bas)',
    combinedMonthly: 'Totalt per månad',
    implementationOneTime: 'Införande (engångs)',
    indicativeOnly: 'Endast vägledande — bekräfta dina system så fastställer vi exakt klass.',
    billedPerObject: 'Debiteras per aktivt objekt',
    objectChargeNote: 'Debiteras endast så länge objektet är aktivt, och rabatteras aldrig.',
    commitmentTerm: 'Bindningstid',
    termMonthly: 'Månadsvis',
    termAnnual: 'Årsvis',
    termTwoYear: '2 år',
    saveShort: 'spara {percent}',
    volumeLabel: 'Volym ({locations} platser)',
    earlyAdopter: 'Tidig kund',
    volumeNotApplied: 'Volymrabatt {percent} tillämpas inte — bindningstiden ger mer',
    termNotApplied: 'Bindningsrabatt {percent} tillämpas inte — volymen ger mer',
    crewStackReady: 'Din Crew-uppsättning är klar',
    crewCurveNote: 'Crew prissätts på en fallande kurva — första platsen till ankarpriset, därefter varje tillagd plats billigare per skikt',
    crewSubstrateNote:
      'Löneberedskap i flera regioner, schemaläggning och HR-drift på en operativ bas.',
    modelledHeading: 'Modellberäkning — inte ett uppmätt utfall',
    modelledNote:
      'Varje siffra här är en planeringsmodell byggd på publicerade antagandeintervall, redovisade per rad nedan. Sundae har ännu inte publicerat verifierade kundresultat: använd det för att rama in samtalet med era egna siffror, inte som en prognos.',
    basisLabel: 'Underlag',
  },
  bn: {
    yourConfiguration: 'আপনার কনফিগারেশন',
    monthlyInvestment: 'মাসিক বিনিয়োগ',
    coreRail: 'Core ধারা',
    crewRail: 'Crew ধারা (পরিচালন ভিত্তি)',
    combinedMonthly: 'সম্মিলিত মাসিক',
    implementationOneTime: 'বাস্তবায়ন (এককালীন)',
    indicativeOnly: 'শুধু নির্দেশক — আপনার সিস্টেম নিশ্চিত করুন, আমরা সঠিক শ্রেণি নির্ধারণ করব।',
    billedPerObject: 'প্রতি সক্রিয় অবজেক্টে বিল',
    objectChargeNote: 'অবজেক্ট সক্রিয় থাকা অবস্থাতেই কেবল চার্জ হয়, এবং কখনও ছাড় পায় না।',
    commitmentTerm: 'প্রতিশ্রুতির মেয়াদ',
    termMonthly: 'মাসিক',
    termAnnual: 'বার্ষিক',
    termTwoYear: '২ বছর',
    saveShort: '{percent} সাশ্রয়',
    volumeLabel: 'পরিমাণ ({locations} লোকেশন)',
    earlyAdopter: 'প্রাথমিক গ্রাহক',
    volumeNotApplied: 'ভলিউম ছাড় {percent} প্রযোজ্য নয় — মেয়াদের ছাড় বেশি',
    termNotApplied: 'মেয়াদের ছাড় {percent} প্রযোজ্য নয় — ভলিউম ছাড় বেশি',
    crewStackReady: 'আপনার Crew স্ট্যাক প্রস্তুত',
    crewCurveNote: 'Crew ক্রমহ্রাসমান বক্ররেখায় মূল্যায়িত হয় — প্রথম লোকেশন অ্যাঙ্কর মূল্যে, এরপর প্রতিটি অতিরিক্ত লোকেশন ব্যান্ড অনুযায়ী সস্তা',
    crewSubstrateNote:
      'একই পরিচালন ভিত্তিতে বহু-অঞ্চল বেতন প্রস্তুতি, সময়সূচি ও HR পরিচালনা।',
    modelledHeading: 'মডেল-ভিত্তিক অনুমান — পরিমাপ করা ফল নয়',
    modelledNote:
      'এখানে প্রতিটি সংখ্যা প্রকাশিত অনুমান-পরিসর থেকে গড়া একটি পরিকল্পনা মডেল, নিচে প্রতি লাইনে দেখানো। Sundae এখনও যাচাই করা গ্রাহক-ফল প্রকাশ করেনি — এটিকে পূর্বাভাস নয়, বরং নিজের সংখ্যা দিয়ে আলোচনা সাজানোর সূচনা হিসেবে ধরুন।',
    basisLabel: 'ভিত্তি',
  },
  th: {
    yourConfiguration: 'การกำหนดค่าของคุณ',
    monthlyInvestment: 'ค่าใช้จ่ายต่อเดือน',
    coreRail: 'สาย Core',
    crewRail: 'สาย Crew (ฐานปฏิบัติการ)',
    combinedMonthly: 'รวมต่อเดือน',
    implementationOneTime: 'การติดตั้งใช้งาน (ครั้งเดียว)',
    indicativeOnly: 'เป็นเพียงตัวเลขโดยประมาณ ยืนยันระบบของคุณแล้วเราจะกำหนดระดับที่แน่นอน',
    billedPerObject: 'คิดค่าบริการต่อออบเจกต์ที่ใช้งานอยู่',
    objectChargeNote: 'คิดค่าบริการเฉพาะช่วงที่ออบเจกต์ใช้งานอยู่ และไม่มีส่วนลด',
    commitmentTerm: 'ระยะเวลาผูกพัน',
    termMonthly: 'รายเดือน',
    termAnnual: 'รายปี',
    termTwoYear: '2 ปี',
    saveShort: 'ประหยัด {percent}',
    volumeLabel: 'ปริมาณ ({locations} สาขา)',
    earlyAdopter: 'ลูกค้ากลุ่มแรก',
    volumeNotApplied: 'ส่วนลดตามปริมาณ {percent} ไม่ถูกใช้ เพราะส่วนลดตามระยะเวลาสูงกว่า',
    termNotApplied: 'ส่วนลดตามระยะเวลา {percent} ไม่ถูกใช้ เพราะส่วนลดตามปริมาณสูงกว่า',
    crewStackReady: 'ชุด Crew ของคุณพร้อมแล้ว',
    crewCurveNote: 'Crew คิดราคาแบบขั้นบันไดลดหลั่น สาขาแรกคิดตามราคาตั้งต้น จากนั้นแต่ละสาขาที่เพิ่มจะถูกลงตามช่วง',
    crewSubstrateNote:
      'ความพร้อมด้านเงินเดือนหลายภูมิภาค การจัดตารางงาน และงาน HR บนฐานปฏิบัติการเดียว',
    modelledHeading: 'ตัวเลขจากแบบจำลอง ไม่ใช่ผลที่วัดได้จริง',
    modelledNote:
      'ทุกตัวเลขที่นี่คือแบบจำลองเพื่อการวางแผน สร้างจากช่วงสมมติฐานที่เผยแพร่ไว้ และแสดงที่มาแยกรายบรรทัดด้านล่าง Sundae ยังไม่ได้เผยแพร่ผลลัพธ์ลูกค้าที่ผ่านการตรวจสอบ จึงควรใช้เป็นจุดตั้งต้นในการคุยด้วยตัวเลขของคุณเอง ไม่ใช่การพยากรณ์',
    basisLabel: 'ที่มา',
  },
  ms: {
    yourConfiguration: 'Konfigurasi anda',
    monthlyInvestment: 'Pelaburan bulanan',
    coreRail: 'Laluan Core',
    crewRail: 'Laluan Crew (asas operasi)',
    combinedMonthly: 'Jumlah bulanan gabungan',
    implementationOneTime: 'Pelaksanaan (sekali bayar)',
    indicativeOnly: 'Anggaran sahaja — sahkan sistem anda dan kami akan tentukan kelas tepat.',
    billedPerObject: 'Dicaj bagi setiap objek aktif',
    objectChargeNote: 'Dicaj hanya sepanjang objek aktif, dan tidak pernah didiskaunkan.',
    commitmentTerm: 'Tempoh komitmen',
    termMonthly: 'Bulanan',
    termAnnual: 'Tahunan',
    termTwoYear: '2 tahun',
    saveShort: 'jimat {percent}',
    volumeLabel: 'Volum ({locations} lokasi)',
    earlyAdopter: 'Pelanggan awal',
    volumeNotApplied: 'Diskaun volum {percent} tidak dikenakan — diskaun tempoh lebih tinggi',
    termNotApplied: 'Diskaun tempoh {percent} tidak dikenakan — diskaun volum lebih tinggi',
    crewStackReady: 'Susunan Crew anda sudah sedia',
    crewCurveNote: 'Crew dikenakan kadar menurun — lokasi pertama pada harga sauh, kemudian setiap lokasi tambahan lebih murah mengikut jalur',
    crewSubstrateNote:
      'Kesediaan gaji pelbagai wilayah, penjadualan dan operasi HR atas satu asas operasi.',
    modelledHeading: 'Anggaran model — bukan hasil yang diukur',
    modelledNote:
      'Setiap angka di sini ialah model perancangan yang dibina daripada julat andaian yang diterbitkan, ditunjukkan setiap baris di bawah. Sundae belum menerbitkan hasil pelanggan yang disahkan, jadi gunakannya untuk merangka perbualan dengan angka anda sendiri, bukan sebagai ramalan.',
    basisLabel: 'Asas',
  },
};

/** Falls back to English only for a locale we do not ship. */
export function getQuoteSummaryCopy(locale: string): QuoteSummaryCopy {
  return quoteSummaryCopy[locale] ?? quoteSummaryCopy.en;
}
