import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { supportedLocales } from '../src/lib/locales';
import { getBuyerCopy } from '../src/lib/buyerCopy';
import { getQuoteSummaryCopy } from '../src/lib/quoteSummaryCopy';
import { corePackages, crewSkus, conceptSkus, foresightAction, watchtower } from '../src/data/pricing';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');
const contract = readFileSync(resolve(root, 'src/lib/pricingIntent.ts'), 'utf8');
const names = Object.fromEntries([
  ...Object.values(corePackages), ...Object.values(crewSkus), ...Object.values(conceptSkus), foresightAction, ...Object.values(watchtower),
].map((offer) => [offer.id, offer.name]));
const copies = Object.fromEntries(supportedLocales.map((locale) => {
  const c = getBuyerCopy(locale);
  return [locale, { title: getQuoteSummaryCopy(locale).yourConfiguration, scope:c.bands, review:c.review, note:c.intentNote, terms:c.terms, workforce:c.workforce, payroll:c.payroll }];
}));
const copySource = '// Generated by sundae-pricing/scripts/sync-pricing-handoff.ts. Edit the pricing copy source and resync.\n'
  + `export const pricingIntentCopy = ${JSON.stringify(copies,null,2)} as const;\n`
  + `export const pricingOfferNames: Record<string, string> = ${JSON.stringify(names,null,2)};\n`;
let errors = 0;
for (const repo of ['sundae-pricing','sundae-app','sundae-website']) {
  const destination = resolve(root, '..', repo, 'src/lib');
  if (!existsSync(destination)) { console.log(`Sibling ${repo} unavailable; cross-repo check skipped.`); continue; }
  for (const [file, expected] of [['pricingIntent.ts',contract], ['pricingHandoffCopy.ts',copySource]]) {
    const path = resolve(destination,file);
    if (check) {
      if (!existsSync(path) || readFileSync(path,'utf8') !== expected) { console.error(`Pricing handoff drift: ${repo}/${file}`); errors++; }
    } else writeFileSync(path,expected);
  }
}
if (errors) process.exit(1);
console.log(check ? 'Pricing handoff contract and copy parity passed.' : 'Pricing handoff contract and copy synchronized.');
